.github/workflows/ci.yml
.github/workflows/publish-docker-image.yml
package.json
src/components/OpenLayer.tsx
yarn.lock

Add workflow to publish docker image to Github Packages.
https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images
Add CI workflow:
https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-nodejs

HAI-21 Add github workflow to publish docker image

---

package.json
src/common/components/app/Layout.tsx
src/common/components/app/layout.styles.scss
src/domain/hanke/map/HankeMap.tsx
src/domain/hanke/map/map.styles.scss

removed styled

---

cypress/integration/frontpage.spec.ts
src/common/components/header/Header.styles.scss
src/common/components/header/Header.test.tsx
src/common/components/header/Header.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json
src/pages/HomePage.tsx
yarn.lock

Luo uusi hanke button to header

button link to header

---

.github/pull_request_template.md

Added a pr template. Paradoxically this pr template is not visible in this pr, since it needs to be merged first.

HAI-29 added pr template for github

---

package.json
src/common/components/app/app.scss
src/common/components/map/Map.tsx
src/common/components/map/MapContext.tsx
src/common/components/map/constants.ts
src/common/components/map/controls/ControlPanel.tsx
src/common/components/map/controls/Controls.module.scss
src/common/components/map/controls/Controls.tsx
src/common/components/map/controls/DrawControl.tsx
src/common/components/map/controls/TileLayers.tsx
src/common/components/map/interactions/Draw.tsx
src/common/components/map/types.ts
src/common/types/common.ts
src/domain/hanke/map/HankeDrawer.tsx

- Add clsx-package to dynamically add/remove style classes
- Add two drawing tools: circle and polygon
- Add styles to map controls

HAI-153: Simple drawtools

---

Dockerfile-local

Swiched using nxing:stable instead of the image from rhel.

Hai 181 change image for docker compose

---

cypress/cypress.d.ts
cypress/integration/drawToMap.spec.ts
cypress/integration/frontpage.spec.ts
cypress/support/commands.ts
src/common/components/map/Map.tsx
src/common/components/map/controls/DrawControl.tsx
src/common/components/map/layers/VectorLayer.tsx
src/domain/map/HankeDrawer.tsx
src/domain/map/Layers/DataLayers.tsx

Draw simple polygon and checks that SaveButton will appear.
Also add className to set layer name inside of openlayers instance.

HAI-243: Add simple E2E test to map

---

src/common/components/dropdown/Dropdown.tsx
src/common/utils/api.ts
src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/Form.tsx
src/domain/hanke/edit/Form0.tsx
src/domain/hanke/edit/Form2.tsx
src/domain/hanke/edit/Form4.tsx
src/domain/hanke/edit/PropTypes.tsx
src/domain/hanke/edit/reducer.ts
src/domain/hanke/edit/selectors.ts
src/domain/hanke/edit/thunks.ts
src/domain/hanke/edit/types.ts
src/domain/hanke/edit/utils.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

- Hankkeen haitat page for form
- Refactored form fields to use enums

HAI-198: Hankkeen haitat -page

---

src/common/components/datePicker/DatePicker.tsx
src/common/components/dropdown/Dropdown.tsx
src/common/components/dropdown/dropDown.styles.scss
src/common/components/textInput/TextInput.tsx
src/domain/hanke/edit/Form.styles.scss
src/domain/hanke/edit/Form0.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Hai 268 ver2

---

src/common/components/footer/Footer.tsx

To test automatic deploy to azure openshift.

HAI-275 added text to test automatic deploy

---

src/common/components/map/Map.tsx
src/common/components/map/MapContext.tsx
src/common/components/map/constants.ts
src/common/components/map/controls/DrawControl.tsx
src/common/components/map/interactions/Draw.tsx
src/common/components/map/types.ts

- Add square
- Rename Drawtooltype selections

HAI-168: Add Square to map geometries

---

src/common/components/dropdown/Dropdown.tsx
src/common/components/dropdown/DropdownMultiselect.tsx
src/common/components/textInput/TextInput.tsx
src/domain/hanke/edit/Form.tsx
src/domain/hanke/edit/Form0.tsx
src/domain/hanke/edit/Form1.tsx
src/domain/hanke/edit/Form2.tsx
src/domain/hanke/edit/Form3.tsx
src/domain/hanke/edit/Form4.tsx
src/domain/hanke/edit/thunks.ts
src/domain/hanke/edit/types.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

- Update tyomaatyyppi to array and add multiselect-component

HAI-197: Fix työmaatyyppi-multiselect

---

package.json
src/domain/hanke/edit/Form.styles.scss
src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/Form.tsx
src/domain/hanke/edit/Form0.tsx
src/domain/hanke/edit/Form1.tsx
src/domain/hanke/edit/Form2.tsx
src/domain/hanke/edit/reducer.ts
src/domain/hanke/edit/types.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json
yarn.lock

Simple implementation of Contacts page. OrganisaatioId and organisaatioNimi UI will be implemented right after this PR.

HAI-196: Add contacts page to form

---

src/common/components/footer/Footer.tsx

Just removed HAI-275 from footer.

HAI-275 removed obsolete text in footer

---

src/domain/hanke/edit/Form0.tsx
src/domain/hanke/edit/validations.ts

removed code, which broker form

HAI-381: Bug fix: formia ei voi navigoida eteenpäin

---

src/common/components/datePicker/DatePicker.tsx
src/common/components/dropdown/Dropdown.tsx
src/common/components/textInput/TextInput.tsx
src/domain/hanke/edit/Form.styles.scss
src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/Form.tsx
src/domain/hanke/edit/Form0.tsx
src/domain/hanke/edit/FormButtons.tsx
src/domain/hanke/edit/validations.ts

This should fix all other than button colors
https://helsinkisolutionoffice.atlassian.net/browse/HAI-393

HAI-393: Hankeform fixes

---

src/common/utils/yup.ts
src/domain/hanke/edit/Form.styles.scss
src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/Form2.tsx
src/domain/hanke/edit/hankeSchema.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Add basic validations to contacts in hankeform.

HAI-365: Contact validations

---

src/domain/hanke/edit/Form.test.tsx

Test validation error translations work correctly

HAI-347: Test validation message

---

package.json

https://github.com/pmndrs/react-spring/issues/1078

HAI-312: Fix notification crash in production env

---

src/common/components/map/controls/Controls.module.scss
src/common/components/map/controls/LayerControl.tsx
src/domain/map/HankeDrawer.tsx
src/domain/map/Layers/Ortokartta.tsx

- Add ortokartta-layer to map
- Minor tweaks to map control ui

HAI-428: Ortokartta

---

src/common/utils/api.ts
src/domain/hanke/edit/Form0.tsx
src/domain/hanke/edit/Form3.tsx
src/domain/hanke/edit/Form4.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/types.ts
src/domain/hanke/edit/utils.ts
src/domain/hanke/list/HankeList.tsx
src/domain/map/HankeMap.tsx
src/domain/map/types.ts
src/domain/types/hanke.ts

Rajapinnasta haetaan data minkä perusteella kartalla näkyy hankkeiden geometriat.
Avattu PR keskustelua varten:
- hankkeet-datan nostaminen yhteiseksi kartalle, hankelistalle ja editointinäkymille?
- testaaminen -- kartalla olevat hankkeet piirtyvät canvas-elementin sisään enkä ole keksinyt miten niitä voisi accessoida validoinnin vuoksi. Screenshot testit testaamaan kuvien eroavaisuuksia baselinestä?

Hai 452 Oikean hankedatan hakeminen rest-rajapinnasta kartalle

---

src/domain/hanke/edit/Form2.tsx
src/domain/hanke/edit/thunks.ts

- response.data needs to be explicitly returned

API object returns entire AxiosResponse

---

src/domain/map/HankeMap.tsx

Will be refactored once dateRangeControl has been implemented

Retrieve projects with a default daterange

---

src/common/components/app/layout.styles.scss
src/common/components/container/Container.module.scss
src/common/components/container/Container.tsx
src/pages/HomePage.tsx
src/pages/ProjectPage.tsx
src/pages/ProjectsPage.tsx

- Used container from hds-container, however, this component leaves pages
left-aligned and thus needs specific styling applied. Comments?

Map should be full-width, other pages not;

---

src/common/components/map/Map.tsx
src/domain/map/HankeMap.tsx

- centralized around central railway station
- default zoom level brought closer

Map defaults updated;

---

src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/Form.tsx
src/domain/hanke/edit/Form0.tsx
src/domain/hanke/edit/Form1.tsx
src/domain/hanke/edit/Form2.tsx
src/domain/hanke/edit/Form3.tsx
src/domain/hanke/edit/Form4.tsx
src/domain/hanke/edit/FormButtons.tsx
src/domain/hanke/edit/FormContainer.tsx
src/domain/hanke/edit/Notification.tsx
src/domain/hanke/edit/hooks/useFormPage.ts
src/domain/hanke/edit/types.ts
src/pages/ProjectPage.tsx

- Refaktoroitu hankelomakkeen koodia paremmin testattavaksi
- Lisätty testitapauksia
- Lisätty useFormPage-hookki joka ajaa validoinnit sivun unmountissa. Tällä pääsi eroon rumasta setTimeout -viritelmästä.

HAI-535: Hankelomakkeen laajemmat testit

---

src/common/components/map/controls/LayerControl.tsx
src/domain/map/HankeDrawer.tsx
src/domain/map/HankeMap.tsx
src/domain/map/Layers/DataLayers.tsx
src/domain/map/Map.test.tsx
src/domain/map/constants.ts
src/domain/map/hooks/useMapLayers.ts
src/domain/map/reducer.ts
src/domain/map/selectors.ts
src/domain/map/types.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Avattu PR keskustelua varten,
testien toteutus vielä puuttuu.

Hai 532 - kartan tasovalinnan refaktorointi

---

cypress/integration/homePage.spec.ts
cypress/support/index.ts
package.json
src/common/components/app/App.tsx
src/common/components/app/Layout.tsx
src/common/components/footer/Footer.tsx
src/index.tsx
src/pages/HomePage.tsx
yarn.lock

- Lisätty cypress-axe ja react-axe
- React-axe tulostaa selaimen konsoliin virheet niin ne on sieltä helppo huomata ja korjata
- Cypress-axe varmistaa, että on varmasti huomattu ja korjattu
- Testit on lisättävä cypressiin jokaiselle sivulle erikseen. Tein esimerkin etusivusta.

HAI-588: Automaattiset Axe -saavutettavuustestit

---

src/common/components/autocomplete/Autocomplete.tsx
src/domain/hanke/edit/Form2.tsx
src/domain/hanke/edit/OrganizationSelect.tsx
src/domain/hanke/edit/types.ts
src/domain/types/hanke.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

- OrganizationSelect -komponentti, josta voi valita oman organisaation. Checkbox on toteutettu komponentin sisäisellä statella.
- Parannettu kontaktien tyypityksiä ja poistettu ts-ignoret. 
- Autocomplete bugittaa, se ei päivity jos defaultValue muuttuu, eli pitäisi ehkä lisätä kontrolloitu value. Tämän huomaa kun vaihtaa valinnan omasta organisaatiosta valittuun. Autocompleten pitäisi tyhjentyä. 
- Testit puuttuu vielä. Tekisin mielelään tuon Autocomplete -korjauksen yhteydessä (https://helsinkisolutionoffice.atlassian.net/browse/HAI-620).

HAI-306: Oman organisaation valitseminen

---

src/common/components/autocomplete/Autocomplete.tsx
src/domain/hanke/edit/OrganizationSelect.test.tsx
src/domain/hanke/edit/OrganizationSelect.tsx

En saanut uncontrolled-controlled -varoitusta poistettua. Liittyy ymmärtääkseni siihen kun value asetetaan tyhjäksi, mutta en keksi miten ComboBoxia saisi muuten tyhjennettyä.

HAI-620: Organisaatiovalinnan testit ja Autocompleten korjaus

---

src/domain/hanke/list/HankeListComponent.tsx

returning code

---

.env
Dockerfile-local
package.json
src/index.tsx
yarn.lock

Kyseessä on
Sentry-clientin käyttöönotto. .env muuttujasta jätetty sentryn dns entry vielä toistaiseksi pois.
Juteltava Teemun kanssa tuon "salaisuuden" (?) jakamisesta kontille.

HAI-559 basic installation of sentry;

---

src/domain/auth/authService.test.ts
src/domain/auth/authService.ts
src/domain/auth/components/OidcCallback.tsx

Kyseessä on
Laitetaan päälle PCKE-kirjautuminen ja silentRenew pois päältä.

HAI-768: Enable PKCE

---

src/domain/hanke/list/Hankelista.styles.scss

Kyseessä on
Linkin väri vaihdetaan siniseen

link color

---

cypress/integration/hankeMap.spec.ts
src/common/components/map/controls/DateRangeControl.tsx
src/common/components/map/controls/LayerControl.tsx
src/domain/map/HankeMap.tsx
src/domain/map/Map.module.scss
src/domain/map/components/HankeSidebar/HankeSidebar.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Kyseessä on
Lisätään karttasivuun axe-testit. 
- [] Muuttujat ovat kuvaavasti nimettyjä eikä koodi sisällä kirjoitusvirheitä

HAI-600: Karttasivun Axe

---

cypress/cypress.d.ts
cypress/integration/editHankePage.spec.ts
cypress/integration/form.spec.ts
cypress/integration/hankelist.spec.ts
cypress/integration/login.spec.ts
cypress/support/commands.ts
cypress/support/index.ts
cypress/tsconfig.json
package.json
src/domain/hanke/list/Hankelista.styles.scss
src/domain/hanke/list/Table.tsx
yarn.lock

HAI-697: Cypress add login to each page

---

src/common/components/app/App.tsx

Kyseessä on
Disabloi cachen react-querysta

HAI-823: Disable query cache

---

src/common/components/app/App.tsx
src/common/components/app/Layout.tsx
src/common/components/app/app.scss
src/common/components/app/layout.styles.scss
src/common/components/spinner/OverlaySpinner.tsx
src/common/components/spinner/Styles.module.scss
src/common/redux/rootReducer.ts
src/domain/app/App.tsx
src/domain/app/Spinner.tsx
src/domain/app/reducer.ts
src/domain/app/selectors.ts
src/domain/hanke/edit/thunks.ts

Hai 703:UI: "Laskenta käynnissä"-spinneri laskennan ajaksi näkyviin

---

src/common/components/app/app.scss
src/common/components/app/layout.styles.scss
src/common/components/map/Map.tsx
src/common/components/map/controls/LayerControl.tsx
src/domain/map/HankeMap.tsx
src/domain/map/components/Layers/Kantakartta.tsx
src/domain/map/components/Layers/Ortokartta.tsx

Kyseessä on
- Lisätään kartan aineistot ja niille UI
- Scrollausbugin korjaus
- Poistetaan submit kartan tasovalikosta

HAI-650: Kartan copyright

---

src/domain/map/components/HankeSidebar/HankeIndexes.test.tsx
src/domain/map/components/HankeSidebar/HankeIndexes.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Kyseessä on
- Asetetaan perusIndeksi ruuhkautumisindeksiksi
- Haetaan kiertoreittitarpeen lokalisaatio dynaamisesti
- testit validoimaan lokalisaation toimivuus

Hai 657 ruuhkautuminen ja kiertoreittitarpeet

---

README.md
src/common/components/header/Header.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json
src/pages/HomePage.test.tsx
src/pages/HomePage.tsx

HAI-898: Haitaton 2.0 nimeäminen Haitaton Beta:ksi

---

src/pages/HomePage.tsx

Kyseessä on
Rendataan kartta etusivulle

HAI-896: Kartta etusivulle

---

src/domain/hanke/edit/EditDisabledNotification.tsx
src/domain/hanke/edit/Form.styles.scss
src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/Form.tsx
src/domain/hanke/edit/Form0.tsx
src/domain/hanke/edit/thunks.ts
src/domain/hanke/edit/utils.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

HAI-880: Disabloidaan tallentaminen jos hanke on jo alkanut

---

src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/hankeSchema.ts

HAI-645: Haitta-aika validoinnit

---

src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/hankeSchema.ts

HAI-645: Tarkemmat haittapäivien validoinnit

---

src/domain/map/components/HankeDrawer/HankeDrawer.tsx
src/domain/map/components/interations/FitSource.tsx

Kyseessä on
Hankkeen muokkauksessa keskittää kartan näkymän piirrettyihin geometrioihin,

HAI-901: Keskitä piirretyt geometriat kartalle

---

src/domain/map/components/Layers/HankeLayer.tsx
src/domain/map/utils/geometryStyle.ts

Kyseessä on
- Injektoidaan indeksi osaksi hankkeen featureiden propertieseja kun featureja ollaan lisäämässä hankkeiden vektorilayeriin.

Hai 752 - välitetään indeksi styleFunctionin käytettäväksi

---

src/domain/hanke/edit/Form1.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Kyseessä on
- Ohjeistusteksti kartan piirtosivulle

HAI-891 Ohjeistusteksti kartan piirtosivulle

---

.stylelintrc.json
package.json
yarn.lock

Kyseessä on
Yarn audit paljasti haavoittuvuuksia NPM-paketeissa. Tämä korjaa ne kaikki.

HAI-832: NPM pakettien päivitys auditin perusteella 

---

src/common/components/app/app.scss

HAI-973: UI scroll-bar sivusuunnassa pois

---

src/domain/hanke/edit/Form.styles.scss

HAI-976: UI korjataan piirtosivun sivupalkki

---

src/common/components/app/app.scss
src/common/components/footer/Footer.module.scss
src/common/components/footer/Footer.tsx
src/common/components/map/controls/DateRangeControl.module.scss

HAI-967:look and feel changes

---

src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/Form4.tsx
src/domain/hanke/edit/hankeSchema.ts

Kyseessä on
Oletan että johtui new Date() asettamasta kellonajasta. Tämä ainakin korjasi ongelman.

HAI-974: Haitta-aika antaa väärät alku ja loppuaikamahdollisuudet

---

src/domain/hanke/edit/Form.test.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

HAI-947: Työmaan tiedot -> Hankkeen lisätiedot

---

cypress/integration/login.spec.ts
src/common/components/header/Header.tsx

Kyseessä on
Kirjautuu ulos, sitten sisään testaajatimona ja testaa ettei hankelista lataudu.

HAI-834: Tunnistautumisen-toiminnan testi

---

.github/workflows/ci-main.yml

Kyseessä on
`main` haaran buildaus ja `main` tagatun Docker-imagen build ja push GitHubin Docker rekisteriin.

HAI-815: GitHub workflow for main branch

---

azure-pipelines-dev.yml
azure-pipelines-main.yml

Kyseessä on
Lisätty kaksi skriptiä jotka ohjaava täyttämään Azuren pipelinejä dev ja test

created yml files for dev and main pipelines in Azure

---

.github/workflows/ci-dev.yml
.github/workflows/ci-main.yml

Pienimmästä suurimpaan:
yarn lint
yarn test
yarn build

Muutetaan github actioneiden järjestys

---

.github/workflows/ci-dev.yml

Ei erikseen käynnistetä fronttisovellusta yarnilla kun Docker-composen kautta sovellus on jo pyörimässä

Hai 959 e2e docker compose

---

.github/workflows/ci-dev.yml

Päivitetään käyttämään docker-composea missä ei buildata bäkkäriä

Hai 959 e2e docker compose update

---

.github/workflows/ci-dev.yml
.github/workflows/ci-pr.yml
cypress/integration/accessibility.ts
src/common/components/app/app.scss
src/common/components/footer/Footer.module.scss
src/common/components/footer/Footer.tsx
src/domain/hanke/list/HankeListContainer.tsx

Käyteään HDS:n footeria itse tehdyn sijaan. Korjataan footerin aiheuttamat AXE-virheet

HAI-972: Footerin refaktorointi ja AXE-korjaukset

---

src/domain/hanke/edit/Form.styles.scss
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

tooltip fix and typo fix

---

cypress/integration/E2E.spec.ts
cypress/integration/accessibility.ts

HAI-1010: Axe-saavutettavuustestien korjaus E2E-testien yhteydessä

---

src/common/components/header/Header.tsx

https://helsinkisolutionoffice.atlassian.net/browse/HAI-1015

HAI-1015: Luo uusi hanke -napin piilottaminen kun muokataan hanketta

---

.github/workflows/ci-dev.yml
.github/workflows/ci-main.yml
.github/workflows/ci-pr.yml
package.json
src/common/components/confirmationDialog/ConfirmationDialog.tsx
src/common/components/header/Header.tsx
src/common/components/map/interactions/FeatureClick.tsx
src/common/routes/AppRoutes.tsx
src/common/routes/LocaleRoutes.tsx
src/domain/auth/components/OidcCallback.test.tsx
src/domain/auth/components/OidcCallback.tsx
src/domain/hanke/edit/FormContainer.tsx
src/domain/hanke/edit/FormNotifications.tsx
src/domain/map/components/HankeSidebar/HankeSidebarContainer.tsx
src/pages/EditHankePage.tsx
src/testUtils/render.tsx
yarn.lock

Updated dependencies after the project had been paused for some time

Hai housekeeping

---

src/domain/hanke/edit/FormStepIndicator.tsx
src/domain/hanke/portfolio/HankePortfolio.module.scss
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/hanke/portfolio/__snapshots__/HankePortfolio.test.tsx.snap
src/domain/map/components/HankeSidebar/HankeIndexes.module.scss
src/domain/map/components/HankeSidebar/HankeIndexes.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Hankeindexes are displayed in hankeportfolio for each hanke.

HAI-1093 display hankeindexes in hankeportfolio with a title and tooltip

---

.env

Use tunnistamo for authentication

---

src/domain/homepage/Homepage.module.scss
src/domain/homepage/HomepageComponent.tsx

Add information box on where to send feedback of usage

HAI-1140 info for frontpage instructing where to send feedback

---

src/domain/forms/components/FormPageIndicator.module.scss
src/domain/forms/components/FormPageIndicator.tsx
src/domain/hanke/edit/components/FormStepIndicator.module.scss
src/domain/johtoselvitys/BasicInfo.module.scss
src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/Contacts.module.scss
src/domain/johtoselvitys/Contacts.tsx
src/domain/johtoselvitys/Johtoselvitys.module.scss
src/domain/johtoselvitys/JohtoselvitysContainer.tsx

UI improvements, aligned inputs
Toasts on save and publish

Hai 1128 johtoselvitys improvements

---

src/domain/hanke/newForm/HakemusContainer.tsx

Implement hanke delete on new hanke form based on previous implementation.

HAI-1198 Implement hanke delete on new hanke form

---

src/common/components/header/Header.tsx
src/common/routes/LocaleRoutes.tsx
src/domain/forms/GenericForm.test.tsx
src/domain/forms/GenericForm.tsx
src/domain/hanke/newForm/HakemusContainer.tsx
src/pages/EditHankePage.tsx

Replaced old hanke form with new implementation in hanke edit. Also implemented fetching values of existing hanke in new form when in edit route.

HAI-1218 Take new hanke form into use in hanke edit

---

src/common/components/map/controls/OverviewMapControl.scss
src/common/components/map/controls/OverviewMapControl.tsx
src/domain/hanke/newForm/Geometries.module.scss
src/domain/hanke/newForm/Geometries.tsx
src/domain/map/HankeMap.tsx
src/domain/map/components/AddressSearch/AddressSearchContainer.module.scss
src/domain/map/components/AddressSearch/AddressSearchContainer.tsx

Added overview map control (minimap) to the map used in hanke form.
Also added functionality to overview map to enable moving to another location by clicking on overview map.

HAI-1190 Add overview map (minimap) to the map used in hanke form

---

src/common/components/datePicker/DatePicker.module.scss
src/common/components/datePicker/DatePicker.test.tsx
src/common/components/datePicker/DatePicker.tsx
src/common/utils/date.ts
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/edit/HankeForm0.tsx
src/domain/hanke/edit/HankeForm1.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/utils.ts

Fixed problem in Firefox where date inputs give validation errors no matter what is given as date values.

HAI-1223 Fix validation errors with date inputs in Firefox

---

Dockerfile-dev
Dockerfile-local

The UI needs a newer node version. Bump the versions in the Dockerfiles.

HAI Bump node versions in Dockerfiles

---

package.json
src/common/components/textArea/TextArea.tsx
src/common/components/textInput/TextInput.tsx
src/common/routes/LocaleRoutes.tsx
src/domain/forms/MultipageForm.tsx
src/domain/johtoselvitys/BasicInfo.module.scss
src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/Contacts.tsx
src/domain/johtoselvitys/Geometries.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/ReviewAndSend.tsx
src/domain/johtoselvitys/types.ts
src/domain/johtoselvitys/validationSchema.ts
src/domain/johtoselvitys_old/BasicInfo.module.scss
src/domain/johtoselvitys_old/BasicInfo.tsx
src/domain/johtoselvitys_old/Contacts.module.scss
src/domain/johtoselvitys_old/Contacts.tsx
src/domain/johtoselvitys_old/Geometries.module.scss
src/domain/johtoselvitys_old/Geometries.tsx
src/domain/johtoselvitys_old/Johtoselvitys.module.scss
src/domain/johtoselvitys_old/JohtoselvitysContainer.tsx
src/domain/johtoselvitys_old/ReviewAndSend.tsx
src/domain/johtoselvitys_old/sampleRequest.json
src/domain/johtoselvitys_old/types.ts
src/domain/map/HankeMap.test.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json
src/pages/JohtoselvitysOld.tsx
yarn.lock

Implemented first page of cable report application to match the new design and replaced formik with react-hook-form.
[HAI-1392]: https://helsinkisolutionoffice.atlassian.net/browse/HAI-1392?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

HAI-1392 Implement cable report application first page

---

src/common/components/header/Header.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Profile button and hamburger menu in top bar were missing aria-labels, so added those.

HAI-1413 Add aria-label to Profile button and hamburger menu

---

src/common/components/header/Header.test.tsx
src/common/components/header/Header.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

First batch of translation of finnish, swedish and english translations.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1170
None

HAI-1170 translations

---

src/common/components/radiobutton/BooleanRadioButton.test.tsx
src/common/components/radiobutton/BooleanRadioButton.tsx
src/domain/application/types/application.ts
src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys/validationSchema.ts
src/locales/fi.json

Add a radio button selection group to ask about rock excavation. 
User has to answer either Yes or No.

HAI-1451 Add rock excavation field to cable report application

---

.eslintignore
README.md
package.json
scripts/translate-common.ts
scripts/translate-excel-to-json.ts
scripts/translate-json-to-excel.ts
scripts/tsconfig.json
yarn.lock

Added support of exporting localized text into an xlsx for easier translation. Importing also supported.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-1170
``yarn locales:export``
edit the file
``yarn locales:import``
``git diff``
Won't affect adding of new translation keys. Merges on existing keys only.

HAI-1170 import/export excel translations

---

src/domain/hanke/portfolio/HankePortfolio.module.scss
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/locales/en.json
src/locales/fi.json

Added clear description that filters update the search results for improved accessibility
There is a text visible on hanke list page. It is read by the screen reader.

HAI-1343 Added info text for hanke list filters for improved accessibility

---

src/domain/application/components/ContactsSummary.tsx
src/domain/application/types/application.ts
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/Contacts.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys/validationSchema.ts
src/domain/mocks/data/hakemukset-data.ts

Application contact name is divided into firstName and lastName.

HAI-1595 Change application contact name to first and last name

---

src/common/components/dropdown/DropdownMultiselect.tsx
src/domain/hanke/edit/HankeFormPerustiedot.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

a11y improvement: Add more descriptive texts to buttons texts and labels in tooltips. Enable providing custom button texts in multiselect fields.
Check the tooltips in hanke form and see that they have correct aria labels.

Add more descriptive tooltip button texts and labels

---

src/common/components/datePicker/DatePicker.test.tsx
src/common/components/datePicker/DatePicker.tsx
src/common/components/textInput/TextInput.tsx
src/domain/forms/utils.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx

Enable autofocusing on invalid fields upon pressing next, so that it is easier to find invalid fields in forms.

HAI-1417: Enable autofocusing on invalid fields

---

src/domain/hanke/portfolio/HankePortfolio.module.scss

Design was changes, so the only thing to do in this ticket was to remove some obsolete Css code.
- [ x Other
-

HAI-1340: Remove some obsolete css

---

.github/workflows/ci-main.yml

Remove dependency on "temporarily" disabled e2e tests
Needed to build main-branch to deploy to staging.

HAI Remove dependency on "temporarily" disabled e2e tests

---

src/domain/common/components/hankeInformationView/HankeInformationView.module.scss
src/domain/common/components/hankeInformationView/HankeInformationView.tsx

Made it so that sidebar is justified to the right side of screen instead of being more in the center.

HAI-1627 Improve application view layout

---

src/common/routes/LocaleRoutes.tsx
src/locales/fi.json
src/pages/staticPages/404Page.test.tsx
src/pages/staticPages/404Page.tsx

Added 404 page which is shown when page matching the url is not found.

HAI-1494 Add 404 page

---

src/common/components/header/Header.tsx

Fixed problem where request to Tunnistamo end-session endpoint was aborted because page was reloaded when logging out.

HAI-1691 Fix logout so that user is actually signed out

---

src/common/components/map/controls/Controls.module.scss
src/common/components/map/modules/draw/types.ts
src/domain/johtoselvitys/Johtoselvitys.module.scss

Changed work area draw tools to match the design so that they stand out better.

HAI-1287 Make draw tools easier to see on map

---

src/common/components/Linkbox/Linkbox.tsx

Fix bug in external link icon not showing in Linkbox component

Fix bug in external link icon not showing in Linkbox component

---

src/domain/johtoselvitys/validationSchema.ts

Added validation for cable report application forms text fields that they have to have other characters than white spaces also.

HAI-1749 Validate that text fields do not have just white spaces

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/map/components/OwnHankeMap/OwnHankeMapHeader.tsx

As application areas have not been implemented in full page map yet, link for that is hidden in application view.

HAI-1705 Hide link to full page map in application view

---

src/domain/hanke/list/HankeListContainer.tsx
src/domain/hanke/portfolio/HankePortfolioContainer.tsx

Remove untranslated loading texts
Go to public hanke list and omat hankkeet page and reload the page. There should not be "Ladataan" text.

Remove untranslated loading texts and add spinner

---

src/common/components/datePicker/DatePicker.tsx

Fix date field validation update problem
Make a cable report and try to proceed with a missing end or starting date. There should be validation message.

Fix date field validation update problem

---

src/locales/en.json
src/locales/sv.json

New Swedish and English translations arrived. Merged new translations to translation files.

HAI-1563 Update sv and en translations

---

src/locales/en.json
src/locales/sv.json

There were some translations missing so added those.

HAI-1563 Add missing Swedish and English translations

---

azure-pipelines-build-devtest.yml
package.json
src/common/components/datePicker/DatePicker.tsx
src/domain/application/constants.ts
src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json
src/pages/EditJohtoselvitysPage.tsx
src/pages/Johtoselvitys.tsx
yarn.lock

Haitaton 4

---

azure-pipelines-build-devtest.yml
package.json
src/common/components/datePicker/DatePicker.tsx
src/domain/application/constants.ts
src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json
src/pages/EditJohtoselvitysPage.tsx
src/pages/Johtoselvitys.tsx
yarn.lock

Revert the revert, effectively re-introducing the changes.
This reverts commit df35cdacef59e971b3f291a727a53c92345c5e32.

Production Upgrade 28.6.2023

---

src/common/components/footer/Footer.tsx
src/common/components/text/Text.module.scss
src/common/components/text/Text.tsx
src/common/routes/LocaleRoutes.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json
src/pages/staticPages/AccessibilityPage.tsx
src/pages/staticPages/InfoPage.tsx
src/pages/staticPages/ManualPage.tsx
src/pages/staticPages/PrivacyPolicyPage.tsx

Updated static pages (Manual and support, About Haitaton, Accessibility statement, Privacy policy) to match designs and updated their content.

HAI-1766 Update static pages to match designs

---

src/common/components/map/modules/draw/DrawInteraction.tsx

Removed snap interaction as it was not needed and made it so that modifying geometries is deactivated while drawing is active.
Go to draw work areas to cable report application form, and make sure that they can be drawn so that they are touching each other.

HAI-1630 Make it possible to draw work areas right next to each other

---

Dockerfile
scripts/env.sh

Platta requires a new Dockerfile for the new pipelines.

HAI-1843 Add new Dockerfile for platta

---

README.md

Update README. Add description on what Haitaton is.

HAI-1779 Update readme

---

README.md
src/locales/en.json
src/locales/sv.json

HAI-1944 Update translations

---

src/common/components/checkbox/Checkbox.tsx
src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/edit/components/BasicInformationSummary.tsx
src/domain/hanke/edit/components/ContactsSummary.tsx
src/domain/mocks/data/hankkeet.ts

Made changes:
- Get hanke start and end date directly from API response
- Fix contact type not showing as yhteystiedot.contactType.null if null

HAI-1576 Check that hanke form summary page has everything that should be there

---

src/domain/hanke/accessRights/AccessRightsView.tsx

Props that should be named ariaHidden and ariaLabel were named aria-hidden and aria-label, so fixed that.

Fix prop names in Icon components in AccessRightsView component

---

cypress/integration/E2E.spec.ts
src/domain/application/components/PreFilledContactSelect.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/edit/components/ContactsSummary.tsx
src/domain/hanke/edit/types.ts
src/domain/hanke/edit/utils.ts
src/domain/johtoselvitys/Contacts.test.tsx
src/domain/mocks/data/hankkeet-data.ts
src/domain/types/hanke.ts

Refactored 
* HankeContact to HankeYhteystieto and 
* HankeSubContact to HankeYhteyshenkilo and 
* HankeContact.alikontaktit to yhteyshenkilot and 
* changed 'email' to 'sahkoposti' and added 'id' for yhteyshenkilo

HAI-2167 Refactored HankeContacts

---

src/domain/forms/components/NewContactPersonForm.tsx
src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/types.ts
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/mocks/data/users-data.json
src/domain/mocks/data/users.ts
src/domain/mocks/handlers.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Add user role/roles to user list in Käyttäjähallinta.
I have only tested this with `yarn start-msw` where it works ok. I do not think that using real backend and API is still operational for adding new contact persons.

HAI-2261 Add user role in user list

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/utils.ts

Editing application is not possible after it has been sent to Allu.
1. Create a new cable report application, fill it and send it to Allu
2. Check that the "Muokkaa hakemusta" button is not available for the application

HAI-2307 Cannot edit application after it has been sent

---

src/domain/auth/profiiliApi.ts
src/domain/auth/useUser.ts

Use session storage to store the verified name.

HAI-2247 Store verified name into session

---

src/domain/application/components/ApplicationList.tsx
src/domain/application/components/ApplicationListItem.tsx
src/domain/application/hooks/useApplications.ts
src/domain/application/types/application.ts
src/domain/hanke/edit/utils.ts
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/mocks/data/hakemukset.ts

Use new `HankkeenHakemus` type for Hanke application list.
Hanke application list should work as before. NOTE: API is not yet changed (HAI-2243).

HAI-2244 New type for hanke applications

---

src/domain/johtoselvitys_new/Attachments.tsx
src/domain/johtoselvitys_new/BasicInfo.module.scss
src/domain/johtoselvitys_new/BasicInfo.tsx
src/domain/johtoselvitys_new/Contacts.module.scss
src/domain/johtoselvitys_new/Contacts.test.tsx
src/domain/johtoselvitys_new/Contacts.tsx
src/domain/johtoselvitys_new/Geometries.module.scss
src/domain/johtoselvitys_new/Geometries.test.tsx
src/domain/johtoselvitys_new/Geometries.tsx
src/domain/johtoselvitys_new/JohtoselvitysContainer.tsx
src/domain/johtoselvitys_new/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys_new/ReviewAndSend.tsx
src/domain/johtoselvitys_new/types.ts
src/domain/johtoselvitys_new/utils.ts
src/domain/johtoselvitys_new/validationSchema.ts
src/pages/EditJohtoselvitysPage.tsx
src/pages/Johtoselvitys.tsx

Duplicated johtoselvitys form files to be used when ACCESS_RIGHTS feature is on, so that new features can be done there without breaking production version.

HAI-2249 New version of johtoselvitys form for building kortisto feature

---

src/domain/hanke/portfolio/HankePortfolioContainer.tsx

Added loading spinner to Omat hankkeet list when loading data.

HAI-2034 Add loading spinner to Omat hankkeet list when loading data

---

src/domain/mocks/handlers.ts

Added the forgotten Sonarcloud complaint fix.

HAI-2302 new api for application sending

---

src/locales/fi.json
src/pages/staticPages/InfoPage.tsx

Updated release information on /fi/tietoja page.
Check the "Tietoja Haitattomasta" page - there should be the new texts as described in the Jira issue.

HAI-2404 New release version information texts

---

src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Imported new translations from the excel file.

HAI-2367 New translations

---

src/locales/en.json
src/locales/sv.json

Added missing translations for `invitationSentLong`.

HAI-2367 Added missing translation

---

src/common/utils/form.test.ts
src/common/utils/yup.ts
src/domain/application/yupSchemas.ts
src/domain/hanke/edit/hankeSchema.ts
src/domain/homepage/Homepage.test.tsx
src/domain/johtoselvitys_new/validationSchema.ts
src/locales/fi.json
src/types/yup-extensions.d.ts

Added validation for phone number by extending yup string schema and applied phone validation for all phone number fields.
Added validation for maximum length of yhteyshenkilo names in johtoselvitys form.

HAI-2530 Add validation for phone number and max lenght for yhteyshenkilo name in johtoselvitys form

---

package.json
src/common/components/map/utils.test.ts
src/common/components/map/utils.ts
yarn.lock

There were some edge cases where polygons were not detected as self-intersecting even though they were. Fixed that by using turf/kinks function instead of turf/unkinkPolygon.
1. Create new johtoselvitys
2. Draw different self-intersecting and not self-intersecting polygons and save the form and check that if frontend validation does not catch the issue that there is no error from backend either.

HAI-2484 Fix detecting self-intersecting polygons

---

src/domain/application/components/ApplicationListItem.module.scss
src/domain/application/components/ApplicationListItem.tsx
src/domain/common/components/hankeInformationView/HankeInformationView.module.scss

Fixed styles in hakemus list so that it behaves better in different screen sizes.
Check hakemus list in different screen sizes to see if it is looking good.

HAI-2534 Fix responsivity in hakemus list

---

src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Added missing or errornous translations.

HAI-2531 Fixed missing or errornous translations

---

package.json
src/common/components/fileDownloadList/FileDownloadList.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/components/summary/KaivuilmoitusAttachmentSummary.tsx
src/domain/application/types/application.ts
src/domain/kaivuilmoitus/Attachments.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/ReviewAndSend.tsx
src/domain/kaivuilmoitus/validationSchema.ts
src/locales/fi.json
src/testUtils/helperFunctions.tsx

* Attachment form section
* Attachment summary form section
* Attachment application view section
Create or open kaivuilmoitus. See that adding/removing/opening attachments works as described in Jira (description in parent issue and in Figma). Also, check the summary section of the application form and application view.

HAI-2378 Attachments and additional info section

---

package.json
src/index.tsx
yarn.lock

* Sentry 8.1.0
* add Sentry console capture and React route integrations in order to capture more errors in UI
* in `package.json` change `start` script to have `REACT_APP_DISABLE_SENTRY=0` instead of `1`
* launch the backend via `docker-compose up haitaton-hanke smtp4dev`
* launch the frontend via `yarn start`
* log in Haitaton
* check  Sentry that there are no 404 or 504 errors from API calls: https://city-of-helsinki.sentry.io/issues/?environment=development&project=5617533&referrer=sidebar&statsPeriod=5m (there might be some errors about `No skip link target` or `undefined` but those can be ignored for now)
* stop the backend
* try to use the frontend (e.g. refresh the page)
* there should come 504 Axios errors in Sentry: https://city-of-helsinki.sentry.io/issues/5363181606/events/?env …

HAI-2570 Sentry error capturing improvements

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/ApplicationViewContainer.tsx

Fixes previous error from merging.

HAI-2519 Show user access rigths on application page - fixup

---

src/common/components/fileUpload/FileListItem.module.scss
src/common/components/fileUpload/FileUpload.module.scss
src/common/components/fileUpload/FileUpload.tsx
src/domain/hanke/edit/HankeFormPerustiedot.tsx
src/domain/johtoselvitys/Geometries.tsx

Small layout fixes to 320px screen size. More information in the Jira ticket.
More information in the ticket.

HAI-1431: Layout fixes for the 320px screen size

---

src/common/components/fileUpload/FileListItem.module.scss
src/common/components/fileUpload/FileUpload.module.scss
src/common/components/fileUpload/FileUpload.tsx
src/domain/hanke/edit/HankeFormPerustiedot.tsx
src/domain/johtoselvitys/Geometries.tsx
src/pages/SkipLinks.test.tsx
src/pages/staticPages/404Page.tsx
src/pages/staticPages/MaintenancePage.tsx

Add missing skip links to pages. Adds unit test file for testing that skip links exist.
- [ x Other
Tests should pass.

HAI-1493: Add missing skip link targets and unit test file for skip links

---

src/locales/en.json
src/locales/sv.json

Add missing translations for HAI.01.10 release version.

HAI-2631 Add missing translations for the texts that are part of the HAI.01.10 release

---

src/domain/application/components/ApplicationMap.tsx
src/domain/johtoselvitys/Geometries.tsx

Fixed a problem where map in johtoselvitys form areas page would not be centered either on address set on first page or work areas.

HAI-2670 Fix focus in johtoselvitys form map

---

scripts/translate-common.ts
scripts/translate-excel-to-json.ts
src/locales/en.json
src/locales/sv.json

Merge release-branch back to dev

Merge release-branch back to dev

---

.env
src/domain/api/api.ts
src/domain/auth/loginProviderProps.ts

Updated OIDC config to use helsinki tunnistus values

HAI-2650 Update OIDC config to use helsinki tunnistus values

---

src/locales/en.json
src/locales/sv.json

Added [TRANSLATION_PENDING] tags to sv and en text resources where the current translation differs from the Finnish text.

Add [TRANSLATION_PENDING] tags

---

src/domain/common/haittaIndexes/__snapshots__/HaittaTooltipContent.test.tsx.snap
src/locales/fi.json

Add tooltip to cycling index level 1
Can't be tested atm.

HAI-2811 Add tooltip to cycling index level 1

---

src/domain/application/components/ApplicationSendDialog.test.tsx
src/domain/application/yupSchemas.ts
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx

Adjust registry key validation schema and add a test for adding a private person for a johtoselvityshakemus.
1. Create a new johtoselvityshakemus
2. Add a customer ("Työstä vastaava" and/or "Työn suorittaja") as a private person
3. Saving and moving to the next page should work

HAI-2821 Adjust registry key validation schema

---

src/locales/en.json
src/locales/sv.json

Added new sv and en translations.

HAI-2845 New translation for production version

---

src/locales/en.json
src/locales/sv.json

Updated Swedish and English translations.

HAI-1925 Update Swedish and English translations

---

e2e/_setup.ts
e2e/johtoselvitys_tilaus_peruminen.spec.ts
e2e/johtoselvitys_tilaus_taydennyspyynto.spec.ts
playwright.config.ts

Lisätty uudelleen käytettävä funktio hakemuksen tarkistamiselle
Poistettu turha test.beforeall
Korjattu yksi elementin tarkistus sekä timeoutteja
Lisatty taydennyspyyntotesti
Hidastettu webkitilla testaamista testien vakauttamiseksi

lisatty taydennyspyynto seka korjauksia

---

e2e/_setup.ts
e2e/haitaton_suomifi_login.spec.ts
e2e/johtoselvitys_tilaus_kasittely.spec.ts
e2e/johtoselvitys_tilaus_peruminen.spec.ts
e2e/johtoselvitys_tilaus_taydennyspyynto.spec.ts

fixed the environment variable usage
Doesn't affect local testing

HAI-1022 variables and variable usage be identic

---

e2e/_setup.ts
e2e/johtoselvitys_tilaus_peruminen.spec.ts
playwright.config.ts

Named env var usage better
fixed element usage
made reporter more suitable for many situations
- [ x] Bug fix
- [ x] New feature

better naming for envvars, fixed code and reporter more thorough

---

src/locales/en.json
src/locales/sv.json

Update latest English and Swedish translations

HAI-3363 Update latest English and Swedish translations

---

e2e/_setup.ts
e2e/haitaton_suomifi_login.spec.ts
e2e/johtoselvitys_tilaus_kasittely.spec.ts
e2e/johtoselvitys_tilaus_peruminen.spec.ts
e2e/johtoselvitys_tilaus_taydennyspyynto.spec.ts
e2e/uusi_hanke.spec.ts

- Fix for login failure
- Hanke tests added

HAI-3337_uusi_hanke_ta_added

---

src/domain/common/haittojenhallinta/CommonProcedureTips.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormHaittojenHallinta.tsx
src/domain/hanke/edit/components/CommonProcedureTips.tsx
src/domain/hanke/edit/components/Haittojenhallintasuunnitelma.tsx
src/domain/kaivuilmoitus/HaittojenHallinta.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/locales/fi.json

Adds common nuisance control tips for both hanke and kaivuilmoitus forms.
Common nuisance tips can be seen in nuisance control step of hanke and kaivuilmoitus forms.

HAI-1994: Adds common nuisance control tips

---

src/domain/hanke/edit/components/Haittojenhallintasuunnitelma.tsx
src/locales/fi.json

Fix texts in procedure tips and remove extra heading.

HAI-1994 review fixes

---

e2e/_setup.ts
e2e/haitaton_suomifi_login.spec.ts
e2e/johtoselvitys_tilaus_kasittely.spec.ts
e2e/johtoselvitys_tilaus_peruminen.spec.ts
e2e/johtoselvitys_tilaus_taydennyspyynto.spec.ts
e2e/kaivuilmoitus.spec.ts
e2e/kaivuuilmoitus.spec.ts
e2e/uusi_hanke.spec.ts

added kaivuuilmotus testautomation
- [x ] Bug fix
- [x ] New feature
login is now simplified

Hai 3332 kaivuuilmoitus ta

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/taydennys/components/summary/JohtoselvitysAreaSummary.tsx
src/domain/application/taydennys/components/summary/KaivuilmoitusAreaSummary.tsx
src/domain/forms/components/FormPagesErrorSummary.tsx
src/domain/hanke/edit/HankeForm.styles.scss
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormHaittojenHallinta.tsx
src/domain/hanke/edit/HankeFormSummary.tsx
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys/ReviewAndSend.tsx
src/domain/johtoselvitys/components/AreaSummary.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennys.test.tsx
src/domain/johtoselvitysTaydennys/ReviewAndSend.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/ReviewAndSend.tsx
src/domain/kaivuilmoitus/components/AreaSummary.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennys.test.tsx
src/domain/kaivuilmoitusTaydennys/ReviewAndSend.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

This PR makes several changes to text strings in the UI. Please refer to the Jira issue for details.
Please see Jira ticket for individual changes. They should be covered by translations in English and Swedish as well.

HAI-3309: Text changes to UI

---

src/pages/staticPages/AccessibilityPage.tsx

Remove obsolete accessibility statement texts.
Texts updated in accessibility statement page.
[HAI-3432]: https://helsinkisolutionoffice.atlassian.net/browse/HAI-3432?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Removed outdated accessilbity issues

---

e2e/_setup.ts
e2e/johtoselvitys_tilaus_kasittely.spec.ts
e2e/johtoselvitys_tilaus_peruminen.spec.ts
e2e/johtoselvitys_tilaus_taydennyspyynto.spec.ts
e2e/kaivuilmoitus.spec.ts
e2e/kaivuilmoitus_taydennyspyynto.spec.ts
e2e/uusi_hanke.spec.ts

updated ajon nimi, and kaivuilmoitus taydennyspyynto added
- [ x ] Other

HAI-3333. updated ajon nimi, and kaivuilmoitus taydennyspyynto added

---

src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennys.test.tsx

Fix failing tests in the pipeline.

Fix failing tests

---

e2e/johtoselvitys_ja_liite_hankkeelle.spec.ts

Fix failing e2e test that broke during changing the send dialog in HAI-3433

HAI-3433 Fix e2e test

---

nginx/nginx.conf

HAI-1688 Fix error in nginx.conf comment line

---

e2e/haitaton_suomifi_login.spec.ts

HAI3378, HAI11992, HAI2651 in one bundle.
Changed the behaviour of suomifi_login test
- [ x] Other

HAI3378, HAI11992, HAI2651 in one bundle.

---

src/domain/johtoselvitys/BasicInfo.module.scss
src/domain/kaivuilmoitus/Kaivuilmoitus.module.scss

Check that issues mentioned in https://helsinkisolutionoffice.atlassian.net/browse/HAI-3372 comments have been fixed.

HAI-3372 Fix margins in in johtoselvitys and kaivuilmoitus forms basic information page

---

src/domain/homepage/Homepage.module.scss
src/domain/homepage/HomepageComponent.tsx

Let's use Hero component provided by HDS in home page instead of own hero styles.
HDS Hero shown in home page for both logged in and logged out user.

HAI-1665: Add hero component to home page

---

e2e/haitaton_suomifi_login.spec.ts
e2e/johtoselvitys_ja_liite_hankkeelle.spec.ts
e2e/kaivuilmoitus_muutosilmoitus.spec.ts
e2e/kaivuilmoitus_toiminnallinen_kunto.spec.ts
e2e/uusi_hanke.spec.ts

E2E test fixes

---

e2e/_setup.ts
e2e/haitaton_suomifi_login.spec.ts

HAI-3582 Use new labels in E2E tests

---

e2e/_setup.ts

Fix e2e test
