City-of-Helsinki/haitaton-ui

.dockerignore
Dockerfile-local

In this branch, a local dockerfile was added in order to build the site in a container such that it can be used in docker-compose in the future.
To test (without docker-compose):
1. Login to RedHat customer portal 
`docker login registry.redhat.io 
`
(If you do not have an account, you can create it at https://access.redhat.com/)
Note the username you need to use in docker login is not your email, there is a
username, you can find out in your profile in customer portal)
2. Build the image
`docker build -t haitaton-ui -f Dockerfile-local .`
3. Run the image
`docker run -d -p 8000:8000 -t haitaton-ui`
4. Go to localhost:8000 
(Note: This is just to test the dockerfile, the upcoming backend pr will add
docker-compose file as well. If you want to test that, pull the HAI-181 branch
from …

HAI-181 added dockerfile-local for docker-compose to use

---

cypress/integration/editHankePage.spec.ts
cypress/integration/form.spec.ts
src/common/components/header/Header.tsx
src/common/routes/LocaleRoutes.tsx
src/common/types/route.ts
src/domain/hanke/edit/FormContainer.tsx
src/domain/hanke/edit/utils.ts
src/domain/hanke/list/HankeListComponent.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json
src/pages/EditHankePage.tsx
src/pages/HankeListPage.tsx
src/pages/MapPage.tsx
src/pages/NewHankePage.tsx

- Uusi sivu /fi/hanke/:hankeTunnus, eli testaamaan pääset syöttämällä tallennetun hankkeen hanketunnuksen urliin.
- Toteutuksessa hyödynnetään lähes täysin hankkeen luomiseen tarkoitettua koodia
- Käynnissä olevan hankkeen validointi menee hieman sekaisin, koska hankkeen alku -ja loppupäivät voivat olla ennen tätä päivää. Validointi ei ilmoita näistä, koska validointi laukaistaan vain onBlur-eventissä
- Piti tehdä konversio HankeDataDraft->HankeDataFormState koska HankeDataDraftissa yhteystietotyypit voivat olla arvoltaan undefined.

HAI-298: Hankkeen muokkaus-sivu

---

package.json
src/common/components/app/Layout.tsx
src/common/routes/AppRoutes.tsx
src/domain/api/api.ts
src/domain/auth/authService.ts
src/domain/auth/constants.ts
src/domain/auth/useAuth.ts
src/domain/hanke/edit/Form2.tsx
src/domain/hanke/edit/FormContainer.tsx
src/domain/hanke/edit/thunks.ts
src/domain/hanke/list/HankeListContainer.tsx
src/domain/map/HankeDrawerContainer.tsx
src/domain/map/HankeMapContainer.tsx
src/domain/map/thunks.ts
src/setupProxy.js

Tämä on kevyt toteutus jossa on tehty vain pakolliset asiat kirjautumisen ja API-kutsujen testaamiseksi. Puuttuu ainakin vielä tokenin uudistaminen, tallentaminen turvallisesti ja testit.

HAI-629: Use access_token in request headers

---

src/domain/map/HankeMapComponent.tsx
src/domain/map/HankeMapContainer.tsx
src/domain/map/Map.test.tsx

Hankkeiden geometriadatat refaktoroidaan yhdelle VectorLayerille hankkeen klikkausta varten.
Muuten jouduttaisiin looppaamaan kaikkien Mapin vectorLayerit lävitse ja kysellä jokaiselta vectorLayeriltä osuiko pikseli johonkin sen Layerin geometriaan. Nyt pelkästään kysytään sitä yhdeltä Layeriltä kuten kuuluisikin.

Hai 647 - Hankkeiden geometriadatat yhdelle VectorLayerille

---

src/common/components/map/interactions/FeatureClick.tsx
src/common/components/map/interactions/HankeClick.tsx
src/domain/map/HankeMap.tsx

Kun geometriaa klikataan hankekartalla selaimen URI-queryparametri "hanke" muutetaan vastaamaan polygonista löytynyttä "hankeTunnus" arvoa.
Tämä on rajapinta hankkeen tarkempien tietojen sivupaneelin avaamiselle.

Hai 582 - Geometriaa klikkaamalla selaimen osoitteeseen päivittyy hankeTunnus

---

src/domain/hanke/edit/Form.test.tsx
src/domain/map/components/HankeSidebar/HankeSidebar.module.scss
src/domain/map/components/HankeSidebar/HankeSidebar.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Korjattu samalla pieni typo
Ohjataan hankkeen editointisivulle samalla tyylillä kuten hankeList -komponentista

Hai 584 - Sivupalkista voi klikata hankkeen muokkaussivulle

---

src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/Form2.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/utils.ts

Yhteystieto filtteröidään pois kutsusta jos se on empty. eli mikään näistä ( etunimi, sukunimi, email, puhelinnumero, organisaatioNimi) ei ole syötetty. Tämä on meidän form-kirjaston takia koska se lisää tuon Contact-objektin väkisin tuohon array-fieldiin.
Omistaja-tyypin validointiin käytetää requiredContactSchemaa, eli pakollisia pakollisia tietoja ovat etunimi, sukunimi, email ja puhelinnumero.

HAI-607: Korjaus yhteystietojen validointiin ja filtteröintiin

---

src/common/components/map/layers/VectorLayer.tsx
src/domain/common/utils/liikennehaittaindeksi.test.ts
src/domain/common/utils/liikennehaittaindeksi.ts
src/domain/map/components/Layers/HankeLayer.tsx
src/domain/map/components/Layers/Kantakartta.tsx
src/domain/map/utils/geometryStyle.ts

Kyseessä on
Funktiot väri-statuksen selvittämiseksi liikennehaittaindeksin perusteella ja värin selvittäminen väri-statuksen perusteella. Tein esimerkin styleFunktiosta jota voi käyttää (ja käytin) hanke-geometrioiden tyylittelemiseksi.

HAI-723: Värin selvitys liikennehaittaindeksin perusteella

---

src/domain/map/components/HankeSidebar/HankeIndexes.module.scss
src/domain/map/components/HankeSidebar/HankeIndexes.test.tsx
src/domain/map/components/HankeSidebar/HankeIndexes.tsx
src/domain/map/components/HankeSidebar/HankeIndexesContainer.tsx
src/domain/map/components/HankeSidebar/HankeSidebar.module.scss
src/domain/map/components/HankeSidebar/HankeSidebar.tsx
src/domain/mocks/hankeIndexData.ts
src/domain/mocks/hankeList.ts
src/domain/types/hanke.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Kyseessä on
Toteutetaan UI-designin mukainen toteutus hankkeen ali-indekseistä sivupalkkiin -- käyttäen staattista dataa vielä tässä vaiheessa. Seuraavissa askeleissa data haetaan ja poimitaan dynaamisesta backendiltä.
PR avattu tukemaan keskustelua toteutuksesta.
TODO: 
1. Tyylittele taulun joka toinen rivi eri värillä
2. indeksin stylelabel tulee olla yhtä leveä jokaiselle indeksinumerolle

Hai 722 - staattiset sivupalkin indeksitiedot asemoituna

---

src/common/components/app/layout.styles.scss
src/domain/common/utils/liikennehaittaindeksi.ts
src/domain/map/HankeMap.tsx
src/domain/map/components/MapGuide/MapGuide.module.scss
src/domain/map/components/MapGuide/MapGuide.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Kyseessä on
Indeksien värinselitysboksi kartan yläkulmaan.

HAI-900: Indeksien värien selitys kartalle

---

src/common/components/app/App.tsx
src/common/components/app/app.scss
src/common/components/app/theme.ts
src/common/components/confirmationDialog/ConfirmationDialog.tsx
src/common/components/confirmationDialog/ConfirmationDialogUI.tsx
src/domain/hanke/edit/Form.test.tsx
src/domain/hanke/edit/Form.tsx
src/domain/hanke/edit/FormButtons.tsx
src/domain/hanke/edit/FormContainer.tsx
src/domain/map/components/HankeSidebar/HankeSidebar.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Kyseessä on
Lisää ennen indeksinlaskentaa dialogin, joka tarkentaa että indeksit voi laskea vain kerran.
Korjattu myös purkkaratkaisu joka poisti dialogin keskityksen: https://helsinkisolutionoffice.atlassian.net/browse/HAI-678
Pientä refaktorointia ConfirmationDialog-komponenttiin

HAI-737: Indeksilaskennan varmistus

---

cypress/integration/E2E.spec.ts
cypress/support/commands.ts
cypress/tsconfig.json
cypress/utils/formFiller.ts
cypress/utils/indexValidator.ts
src/common/components/confirmationDialog/ConfirmationDialogUI.tsx
src/domain/hanke/edit/Form4.tsx
src/domain/hanke/edit/FormButtons.tsx
src/domain/hanke/edit/FormNotifications.tsx
src/domain/hanke/edit/Notification.tsx
src/domain/types/hanke.ts

Kyseessä on
- E2E-testi mikä piirtää kartalle hankkeen neliönä ja laskee indeksit
- Kirjoitettiin testeille apufunktio formFiller hankkeiden generoimiseen UI:n kautta (ennen manuaalisesti/staattisesti)
--> E2E-testeissä hanke voidaan luoda kutsumalla createHankeFromUI(HankeData, countIndexes)
--> E2E-testejä voidaan laajentaa koskemaan erilaiset haittojen permutaatiot tyyliin:
```
for hanke in Hankkeet:
createHankeFromUI(hanke, countIndexes=true)
validateIndexes(hanke)
```

Hai 959 - E2E-testit pääputkelle, hankkeen luonti ja indeksien laskenta

---

src/domain/map/HankeMap.tsx
src/domain/map/HankkeetProvider.tsx
src/domain/map/HankkeetProviderContext.tsx
src/domain/map/components/HankeSidebar/HankeSidebarContainer.tsx

Instead of a redundant API call.
The call was being previously made because tormaystarkastelutulos was not returned for /hankkeet.

HAI-1111 use hankeData directly from provider state

---

src/common/components/map/Map.tsx
src/common/components/map/controls/MapControl.scss
src/common/components/map/controls/MapControl.tsx
src/domain/map/HankeMap.tsx

Minimap component created to control the bigger map.
The component can be used when drawing geometries but is not added into there yet -- as the geometry drawing canvas is still quite small and will be changed when the new designs are implemented.

HAI-1146 custom minimap to control the bigger map on the main map page

---

src/domain/map/HankeMap.tsx
src/domain/map/components/Layers/HankeLayer.tsx
src/domain/map/components/interations/HighlightFeatureOnMap.tsx
src/domain/map/utils/geometryStyle.ts

Hover your cursor over a geometry on the map. The geometries of the hanke are "highlighted"

HAI-1148 hovered and selected hanke geometries are highlighted

---

src/domain/map/components/HankeSidebar/HankeSidebar.tsx

Modified big map sidebar so that information about organization and type of construction site are always displayed. If they are not present, '-' is shown.

HAI-1149: Always show organization and type of construction site in map sidebar

---

package.json
yarn.lock

Node-sass has been deprecated:
https://sass-lang.com/blog/libsass-is-deprecated
This also stopped me from running this in Docker or directly on my
laptop. Starting a Docker build with an error message about missing
a python executable and running directly on the laptop failed because
arm64 architecture is not supported by node-sass. Using dart-sass
instead solves both of these problems.

Replace node-sass with dart-sass

---

.env

Overriding the environment variable in the cloud environments doesn't
seem to be working, so try to disable the variable in the .env file and
see if that makes any difference.

HAI-1139 Disable the OIDC client ID environment variable

---

src/common/utils/date.ts
src/domain/hanke/newForm/BasicHankeInfo.tsx
src/domain/hanke/newForm/Haitat.tsx

Previously DateInputs have required user to click Select button to confirm date selection. Changed it so that confirmation is not required and just clicking the date selects it.

HAI-1199 Don't require confirmation when selecting dates in new hanke form

---

src/domain/hanke/edit/components/Notification.tsx

Fixed an issue where invisible save notification in hanke form was left covering part of the form even when the notification was closed.

HAI-1209 Fix save notification covering part of the hanke form even when it is closed

---

.env

The only change removing the variable caused was that dev environment broke down as well. At least this confirms that the environment variables are not properly read from the cloud configuration.

Revert "HAI-1139 Disable the OIDC client ID environment variable"

---

.env

The environment variable is now set on the container, but the wrong value is still used in testing. Try to disable the variable again.
Reverts City-of-Helsinki/haitaton-ui#212

Revert "Revert "HAI-1139 Disable the OIDC client ID environment variable""

---

src/domain/map/components/AddressSearch/AddressSearch.test.tsx
src/domain/map/components/AddressSearch/AddressSearch.tsx

Fixed it so that now it is checked if Finnish street name of result includes the search term and if so that name is used, otherwise Swedish street name is used.

HAI-1245 Fix address search only returning Finnish names even if search is in Swedish

---

src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/edit/HankeHaitatForm.tsx
src/domain/map/components/HankeSidebar/HankeIndexes.module.scss
src/domain/map/components/HankeSidebar/HankeIndexes.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Added haitat page to hanke form which displays haittaindexes for the created hanke.

HAI-1279 Implement haitat page to hanke form

---

src/locales/i18n.ts

Removed navigator from language detector detection order options so that users browser language does not affect detection, so that if language is not found from localStorage, sessionStorage or path, fallback language of fi will be used.

HAI-1341 Fix language selection breaking when opening the site first time

---

src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/sampleRequest.json
src/domain/johtoselvitys/types.ts

The backend uses the application type data field to decide which application type it should deserialize the incoming JSON to. Because of technical limitations, the type field needs to be inside the application data, since that's the polymorphic object.

HAI-1295 Add application type to application data

---

src/common/components/header/Header.tsx
src/common/components/text/Text.tsx
src/common/constants/constants.ts
src/domain/forms/MultipageForm.tsx
src/domain/hanke/hankeView/HankeView.tsx
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/homepage/HomepageComponent.tsx
src/domain/mapAndList/MapAndListContainer.tsx
src/pages/staticPages/AccessibilityPage.tsx
src/pages/staticPages/InfoPage.tsx
src/pages/staticPages/PrivacyPolicyPage.tsx
src/pages/staticPages/ReferencesPage.tsx

There is a skip to content accessibility shortcut located in the top bar, which did not have target element id. Added the id and added that id for each page heading element.
Navigate the page using tab key. The first element to receive focus when loading the page should be a link with text "Siirry pääsisältöön" and then pressing enter should move focus to the first h1 element of the page you are on if there is one.

HAI-1421 Add target for skip to content accessibility shortcut

---

src/common/components/map/utils.ts
src/domain/hanke/edit/utils.ts
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/johtoselvitys/components/AreaSummary.tsx
src/domain/map/utils.ts

Incorrect surface area calculation was caused by wrong projection (EPSG:3857) used when calling OpenLayers getArea function, so fixed that to EPSG:3879.

HAI-1491 Fix incorrect surface area calculation for hanke and application areas

---

src/domain/homepage/HomepageComponent.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Add a welcome text for logged in users. The title of the software should be different depending on whether the is logged in or not, though I don't know why.
The difference is whether Haitaton is called 'palvelu' or 'asiointi'/'asiointijärjestelmä'.
The new titles should match the ones in Figma.

HAI-1351 Fix title and subtitle for logged in users

---

src/common/hooks/useForceUpdate.ts
src/common/types/hanke.ts
src/domain/application/types/application.ts
src/domain/application/utils.ts
src/domain/hanke/edit/HankeFormAlueet.tsx
src/domain/johtoselvitys/Geometries.module.scss
src/domain/johtoselvitys/Geometries.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/components/AreaSummary.tsx
src/domain/johtoselvitys/types.ts
src/domain/johtoselvitys/utils.ts
src/domain/map/hooks/useAddressCoordinate.ts
src/domain/map/utils.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

User can name application areas and the name is displayed as that areas tab name. Name can be maximum 30 characters long and if it is longer than that it will be shortened to 30. If no name is given, a default name will be used.
geometry field in applicationData is changed to areas field which contains a list of areas. Each area has a name and geometry fields.
Draw area in cable report application areas page and enter a name for it in the text input. Tab name should be changed to that name.

HAI-1455 Implement naming of cable report application areas

---

src/common/components/app/App.tsx
src/common/components/globalNotification/GlobalNotification.tsx
src/common/components/globalNotification/GlobalNotificationContext.tsx
src/domain/application/components/ApplicationCancel.test.tsx
src/domain/application/components/ApplicationCancel.tsx
src/domain/application/types/application.ts
src/domain/application/utils.ts
src/domain/hanke/hankeView/HankeView.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/mocks/apiError.ts
src/domain/mocks/data/hakemukset-data.ts
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts
src/locales/fi.json
src/testUtils/render.tsx

Implemented functionality that user can cancel new application if it is possible, meaning it is not yet in Allu or if the status is still pending.
If cancelling is not possible, cancel button is not displayed.
After successful cancellation, user is taken in to application list and success notification is shown. If something goes wrong, error message is shown.
1. Create new cable report application and save it but don't send it to Allu: (http://localhost:3001/fi/johtoselvityshakemus?hanke=xxxxx-x for example http://localhost:3001/fi/johtoselvityshakemus?hanke=HAI23-1)
2. Click "Peru hakemus" button and confirm the cancellation in confirmation dialog
3. You should be taken to application list tab in hanke page and success notification should be shown
4. Create new application and send it to …

HAI-1456 User can cancel new application

---

src/domain/application/types/application.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/mocks/data/hakemukset-data.ts

When creating new application hankeTunnus of the hanke for which the application belongs to was part of applicationData of the request body when it should be in the upper level of the body so fixed that.

HAI-1531 Fix hankeTunnus in wrong place when creating new application

---

src/common/components/globalNotification/GlobalNotification.tsx
src/common/components/globalNotification/GlobalNotificationContext.tsx
src/domain/application/components/ApplicationCancel.tsx
src/domain/application/components/ApplicationSaveNotification.tsx
src/domain/hanke/hooks/useNavigateToApplicationList.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/locales/fi.json

There was already error message shown to user if saving application fails, but updated it to match the design and also made it to stay on screen until user dismisses it, so that it won't be missed.

HAI-1159 Show error message to user if saving application fails

---

src/common/components/globalNotification/GlobalNotificationContext.tsx
src/domain/application/components/ApplicationCancel.test.tsx
src/domain/application/hooks/useApplicationSendNotification.tsx
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/locales/fi.json
src/testUtils/render.tsx

Implemented showing better error message to user if sending application to Allu fails. Error notification also stays on screen until it is dismissed.

HAI-1158 Show error message to user if sending application to Allu fails

---

src/domain/map/HankeMap.tsx
src/domain/map/Map.module.scss
src/domain/mapAndList/MapAndListContainer.tsx
src/locales/fi.json

Added missing heading for public hanke map and list pages since it was raised in the accessibility evaluation.
Go to public hanke pages. There should be a heading.

HAI-1440: Add heading for public hanke pages

---

src/common/components/errorLoadingText/ErrorLoadingText.tsx
src/domain/application/components/ApplicationList.module.scss
src/domain/application/components/ApplicationList.tsx
src/domain/application/components/ApplicationListItem.module.scss
src/domain/application/components/ApplicationListItem.tsx
src/domain/application/components/ApplicationStatusTag.tsx
src/domain/application/hooks/useApplications.ts
src/domain/application/types/application.ts
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/hanke/hankeView/HankeView.tsx
src/domain/hanke/hankeView/HankeViewContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/map/HankeMap.test.tsx
src/domain/mocks/data/hakemukset-data.ts
src/domain/mocks/handlers.ts
src/locales/fi.json
src/testUtils/render.tsx

Implemented application list which shows applications for selected hanke. It can be found on applications tab in hanke view.
1. Create application(s) for hanke
2. Navigate to view information of that hanke
3. Check that applications you have created are found in applications tab 
Filtering and sorting of the list as well as grouping different versions of the same application will be implemented later.

HAI-1499 Add application list to hanke view

---

src/domain/application/components/ApplicationCancel.tsx
src/domain/application/types/application.ts
src/domain/application/utils.ts
src/domain/forms/MultipageForm.tsx
src/domain/hanke/edit/HankeFormPerustiedot.tsx
src/domain/hanke/edit/components/BasicInformationSummary.tsx
src/domain/hanke/hooks/useNavigateToApplicationList.ts
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/hanke/vaiheTag/HankeVaiheTag.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/mocks/handlers.ts
src/pages/Johtoselvitys.tsx

User can create cable report application without creating hanke first by going to first page of hanke form and clicking a link to fill application. After first save, hanke for the new application is created in the backend.
1. Go to create new hanke, but on the first page of the hanke form click "täytä hakemus" link.
2. Fill out the cable report application form and check that it can be saved and sent.
3. Check from the hanke list that new hanke is displayed with the name of the new application.
4. Go to the hanke page of the new hanke to check that the new application is found in the application list.

HAI-1570 Enable creating cable report application without hanke existing first

---

package.json
src/locales/i18n.ts
yarn.lock

Adds missing babel dependency to fix local build issue.
Makes changing the language setting update the HTML lang attribute for the screen reader to catch the correct language in the page for update accessibility. 
Open the app in browser. The lang attribute should match the selected language. Change the language from the Header menu. The lang attribute in the html should match the newly changed language.
Tested in Firefox and Chrome with VoiceOver screenreader.

HAI-1419: Make changing the language setting update the HTML lang attribute

---

src/domain/forms/components/Contact.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/johtoselvitys/Contacts.tsx
src/domain/johtoselvitys/Geometries.tsx
src/locales/fi.json

Made contact pages in forms to be more accessible by moving fields under fieldsets: 
* Moved contact information under fieldsets to be more understandable to screen reader. 
* Changed their headings and heading levels to match the changes.
* Moved date pickers in johtoselvitys also under a fieldset
Go over the hanke and johtoselvitys forms. The screenreader should read the headings in correct order and pronounce the fieldset heading when going over the fields.
Tested with MacOS and VoiceOver in Firefox.
- x ] I have ran the tests myself (if applicable)

Add fieldsets to forms to make them more helpful for screen readers

---

src/domain/johtoselvitys/Geometries.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys/types.ts
src/domain/johtoselvitys/utils.ts
src/pages/EditJohtoselvitysPage.tsx

Cable report application is only saved when page is changed if user has made changes since the last save.
Create or edit cable report application and note that application should only be saved on page change when there are changes made to the fields or application areas.

HAI-1507 Save cable report application only if something has changed

---

src/common/components/footer/Footer.tsx
src/common/hooks/useLinkPath.ts
src/common/types/route.ts
src/locales/fi.json

Removed link to References and added link to Haitaton manual. The manual page is not implemented in this task so the link does not go anywhere yet.

HAI-1622 Updated footer to match new design

---

src/domain/application/components/BasicInformationSummary.tsx
src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/Contacts.tsx
src/domain/johtoselvitys/Geometries.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys/validationSchema.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Made modifications to cable report application form by removing postal code and city fields from basic information page. Also updated instruction texts in basic information, areas, and contacts pages.
Make sure that postal code and city fields have been removed from basic information page and that form can be filled and saved.

HAI-1625 Remove postal code and city fields from cable report application forms first page

---

src/domain/map/components/AddressSearch/AddressSearch.test.tsx
src/domain/map/components/AddressSearch/AddressSearch.tsx
src/domain/map/utils.ts

Fixed a problem where address search showed results in swedish when typing a finnish search term with trailing whitespace or street number after street name.

HAI-1629 Fix address search showing swedish results when searching in finnish

---

src/domain/homepage/HomepageComponent.tsx
src/locales/fi.json

Update English aria labels to translated ones. Add couple of missing translation from the home page notification area as well.
Check with screenreader that the labels on the notification and linkboxes on the homepage are read on correct language.

HAI-1347: Update English aria labels to translated ones.

---

src/domain/hanke/hankeIndexes/HankeIndexes.module.scss
src/domain/hanke/hankeIndexes/HankeIndexes.tsx
src/domain/map/components/HankeSidebar/HankeSidebar.tsx

Make HankeSidebar headings semantically correct to improve accessibility
Go through HankeSidebar elements and check that headings are semantically correct.

Make HankeSidebar headings semantically correct to improve accessibility

---

src/domain/hanke/portfolio/HankePortfolio.module.scss
src/domain/hanke/portfolio/HankePortfolioComponent.tsx

Make hanke list cards expand button focusable for it to be more accessible to keyboard user.
Go to hanke portfolio. Scroll though elements with tab key.. The hanke card expand button should be focusable.

Make hanke list cards expand button focusable

---

package.json
src/common/components/map/modules/draw/DrawInteraction.tsx
src/common/components/map/modules/draw/DrawModule.tsx
src/common/components/map/utils.ts
src/domain/johtoselvitys/Geometries.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/types.ts
src/domain/johtoselvitys/utils.ts
src/domain/johtoselvitys/validationSchema.ts
src/locales/fi.json
yarn.lock

When user draws or modifies work area in cable report application form, it is checked if the area is self-intersecting and if it is, an error is displayed. Also user can not move forward in the form in that case.
In cable report application form draw new area or modify existing area so that it's self-intersecting. Check that there is an error text and that it's not possible to move to next page.

HAI-1404 Show error if area is self-intersecting in cable report application

---

src/domain/johtoselvitys/Attachments.tsx

Remove .gt, .dgn and .dwg files from supported types.

HAI-1667 Remove unsupported filetypes

---

src/domain/johtoselvitys/JohtoselvitysContainer.tsx

Fixed problem where attachments could not be uploaded while creating new cable report application.
Create new cable report application, fill the form and add attachments and check in the summary page that attachments have been added.

HAI-1632 Fix attachments not uploaded when creating new cable report application

---

src/common/components/header/Header.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/components/ApplicationCancel.test.tsx
src/domain/application/components/ApplicationCancel.tsx
src/domain/hanke/edit/HankeForm.tsx
src/domain/johtoselvitys/Johtoselvitys.module.scss
src/domain/johtoselvitys/JohtoselvitysContainer.tsx

Fix bug that cancel button loading state was not working. Make cancel button styles more consistent.
Cancel button should be in loading state when adding an attachement to johtoselvitys and switching form page.

Fix bug in cancel button loading state

---

src/common/components/fileDownloadLink/FileDownloadLink.tsx
src/domain/application/applicationView/ApplicationView.tsx

Add loading spinner for fetching the file download link, so the UI does not feel unresponsive when downloading.
Go to an application that is in decision state. Click the pdf download link. The link should turn into a spinner while the link is being created.

Add loading spinner for fetching the file download link

---

src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys/validationSchema.ts

Prevent startTime to be after endTime.
Trying to set wrong dates will not allow moving on to next page. Instead a warning is shown.

HAI-1704 Add validation to application area dates

---

src/common/components/footer/Footer.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Add footer links to manual.
Footer links to manual open the correct link based on selected language. Links open in a new window.

Add footer links to manual.

---

src/common/components/fileList/FileList.test.tsx
src/common/components/fileList/FileList.tsx
src/domain/johtoselvitys/Attachments.tsx

If cable report application has already been sent to Allu, hide delete buttons for uploaded attachments because they can not be deleted in Allu.
Check that delete buttons for uploaded attachments are hidden in application that has been sent to Allu, and are shown for application that has not been sent.

HAI-1741 Hide delete buttons for uploaded attachments if application has been sent

---

src/domain/auth/components/OidcCallback.test.tsx
src/domain/auth/components/OidcCallback.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Fix auth error text translations and add styling.
Go to Suomi.fi login and cancel login or append url with `login_callback?error=access_denied&error_description=Authentication+cancelled+or+failed&state=8729ae448b224a28b63fde15c758aee6` to see the error text.

Fix auth error text translations and add styling.

---

src/domain/hanke/hooks/useNavigateToApplicationList.ts
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx

Save and quit button was hidden in the first page of cable report application form, while it should not, so changed that. Also validate application name when saving and quitting in the first page.
Check that save and quit button (Tallenna ja keskeytä) is visible in the first page of cable report application and that saving and quitting works.

HAI-1744 Show save and quit button also in the first page of cable report application

---

src/domain/forms/MultipageForm.module.scss
src/domain/forms/MultipageForm.test.tsx
src/domain/forms/MultipageForm.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/locales/fi.json

Show inline notification when editing a form that is in pending state.
Edit a form that is in pending state. There should be inline notification on top. It should not show on other form states.
-  [x] I have written new tests (if applicable)

Show inline notification when editing a form that is in pending state

---

src/domain/johtoselvitys/BasicInfo.tsx

First name and last name fields in cable report application forms first page are now read-only if they can be retrieved from Helsinki profile.

HAI-1765 Change first name and last name fields in basic information page to be read-only

---

src/domain/johtoselvitys/Attachments.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/constants.ts
src/domain/johtoselvitys/types.ts
src/domain/johtoselvitys/utils.ts
src/domain/johtoselvitys/validationSchema.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Added validation that cable report application can have maximum of 20 attachments.

HAI-1761 Add validation for maximum number of attachments

---

src/domain/johtoselvitys/JohtoselvitysContainer.tsx

Make sure that previous, next, cancel and save buttons in the bottom stay in loading state until all attachments are uploaded.

HAI-1753 Fix problem where buttons don't stay in loading state when uploading attachments

---

src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx

There was an issue in cable report application form, when user selected the same role again in basic information page, their information would be duplicated and there would be multiple orderers for the application.
In cable report application form, select the same role again (for example if your role is Hakija, select it again from the dropdown) and check from the contacts page that there is no change.

HAI-1790 Fix problem where user could duplicate their information

---

src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

User should not be able to edit their own information in cable report application, after application has been sent to Allu, so disabled those fields in that case.
Check that own information can't be edited in an application that has been sent to Allu.

HAI-1752 Disable editing users own information after application has been sent to Allu

---

package.json
src/domain/application/constants.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/pages/EditJohtoselvitysPage.tsx
src/pages/Johtoselvitys.tsx
yarn.lock

When user is creating new cable report application and if the application has been saved, application id is saved to sessionStorage when user refreshes the page so that user can be redirected to edit view.
Go to create new cable report application and make sure that the application is saved by going to next page. Then refresh the page and check that you are editing the same application you just created.

HAI-1763 Redirect user to edit route on page refresh when creating new cable report application

---

src/common/components/header/Header.tsx
src/domain/auth/components/OidcCallback.test.tsx
src/domain/auth/components/OidcCallback.tsx
src/locales/constants.ts
src/locales/i18n.ts

Changed language detection order so that path is before localStorage so that language in the url path takes priority when detecting UI language.
Paste different language url to browser address bar than UI:s selected language (for example /en/projectportfolio when current language is Finnish) and check that correct page is opened and that UI language is changed to correct one.

HAI-1794 Fix problem where visiting different language url than selected language would show 404 page

---

src/domain/hanke/portfolio/HankePortfolioContainer.tsx

Backend has deprecated support for URLs with trailing slashes, so remove them from the frontend.
Only one such URL seems to be called, the hanke list. Change the URL to one without the trailing slash.

HAI-1833 Remove trailing slash from Hankkeet URL

---

src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx

When saving and quitting validate current page of the form and if it's not valid don't save and quit.
Try to save and quit in cable report application form when there are invalid fields (for example empty text inputs that are required) and check that saving and quitting doesn't go through.

HAI-1789 Make sure that cable report application form is valid before save and quit

---

src/common/components/footer/Footer.tsx
src/common/components/header/Header.tsx

Defined logoLanguage prop for Navigation and Footer components so that Helsinki logo language is changed when UI language is changed.
When changing language to Swedish check that Helsinki logo language is changed to Swedish and otherwise is in Finnish.

HAI-1469 Make Helsinki logo to be language dependant

---

src/common/components/header/Header.tsx
src/locales/fi.json
src/pages/staticPages/ManualPage.tsx

Work instructions link in header was missing aria-label, and manual link in manual page was missing the external link icon, so added those.

HAI-1807 Make sure that external links have aria-labels and correct icons

---

src/common/components/map/controls/Controls.module.scss
src/common/components/map/controls/LayerControl.tsx
src/common/components/map/layers/TileLayer.tsx
src/domain/johtoselvitys/Geometries.test.tsx
src/domain/johtoselvitys/Geometries.tsx
src/domain/map/HankeMap.test.tsx
src/domain/map/HankeMap.tsx
src/domain/map/components/HankeDrawer/HankeDrawer.tsx
src/domain/map/components/Layers/Ortokartta.tsx
src/domain/map/reducer.ts

Added orto map layer to cable report application form and the control to toggle it and base map layer on/off. If both layers are on, the orto map layer is displayed at 50% opacity on top of the base map layer.
Navigate to areas page of cable report application form and check that map layers can be toggled on/off from the menu in top right corner of the map.

HAI-1574 Add possibility to toggle two map layers in cable report application form

---

src/locales/fi.json

Updated work instructions link in nav bar and front page to match the new version of hel.fi site.
Check that work instructions link (Työohjeet) goes here https://www.hel.fi/fi/kaupunkiymparisto-ja-liikenne/tontit-ja-rakentamisen-luvat/tyomaan-luvat-ja-ohjeet when UI language is Finnish. There are no translations for other languages of that page.

HAI-1840 Update work instructions link

---

src/domain/application/attachments.test.ts
src/domain/application/attachments.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx

Check name of each attachment that is being sent and if there already is an attachment of that name in the application don't send that attachment again.
Try to send attachment of same name as exists in cable report application and check in the summary page that there are no duplicates.

HAI-1755 Don't send duplicate attachements in cable report application

---

src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx

Fixed issue in cable report application form where "Work is about" (Työssä on kyse) validation error message would remain even when one of the "Work is about" checkboxes was checked.
Go trough the steps in the Jira issue and check that error message is not shown.

HAI-1839 Fix issue where Work is about validation error remains when it shouldn't

---

src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Added specific error messages for failed attachment uploads in cable report application form. One for bad request (when there is something wrong with the file) and one for error caused by technical reason.

HAI-1841 Add better error messages for failed attachment uploads

---

src/common/components/textInput/TextInput.tsx
src/domain/johtoselvitys/BasicInfo.tsx
src/domain/johtoselvitys/Contacts.module.scss
src/domain/johtoselvitys/Contacts.test.tsx
src/domain/johtoselvitys/Contacts.tsx
src/locales/fi.json

Added button that enables user to copy the information they have entered in the first page of cable report application to other contacts in the contact page.
Also added autocomplete attributes to many of the cable report application text fields.
1. Either create new cable report application or edit a previous one
2. Fill the form up to contacts page
3. There should be "Täytä omilla tiedoilla" button with each customer type and their contacts
4. Press the button and check that information filled in the first page as user's own information is copied to corresponding fields. 

HAI-1835 Add possibility to copy user's own information to other contacts in cable report application

---

src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/mocks/data/users-data.json

Fixed problem where sorting in users rights view table would not work correctly when there are names in both lower and upper case.
Check that users are sorted alphabetically even if there are names like Matti and mauno for example.

HAI-1510 Fix lower and upper case names causing problems in table sorting

---

src/domain/johtoselvitys/Contacts.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx

Fixed a problem in cable report application form where the form would not be saved when user clicked the Täytä omilla tiedoilla button in contacts page and changed form page after that. This was caused by not setting the form fields as dirty.

HAI-1917 Fix problem where form is not saved after filling contact information with user's own information

---

package.json
src/common/routes/AppRoutes.tsx
src/common/routes/PrivateRoute.tsx
src/common/routes/Routes.test.tsx
src/common/routes/constants.ts
src/domain/auth/authService.test.ts
src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/setupTests.ts
yarn.lock

If user tries to access page that requires login, that path is saved to session storage and user is redirected to login and after successful login user is redirected to the path in session storage.
1. When not logged in try to access for example cable report application form: http://localhost:3001/fi/johtoselvityshakemus
2. You should be taken to login and after that to cable report application form

HAI-1311 Redirect user to original route after login

---

src/domain/auth/components/UserIdentify.test.tsx
src/domain/auth/components/UserIdentify.tsx
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Added hanke name and tunnus to notification that is shown after successfully identifying user.

HAI-1941 Show hanke name and tunnus in user identification success notification

---

src/domain/application/components/ApplicationCancel.test.tsx
src/domain/application/components/ApplicationCancel.tsx
src/domain/application/types/application.ts
src/domain/application/utils.ts
src/domain/hanke/hooks/useNavigateToApplicationList.ts
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx

When the only application of a genedated hanke is deleted, backend also deletes the hanke.
If hanke deletion result is defined in the response object. If hanke was deleted, user is directed to hanke listing.
Create johtoselvitys with generated hanke, delete johtoselvitys. Should navigate to hanke list. If hanke is not generated, should work as before (stay at the specific hanke).

HAI-1599 Navigate to hanke list after generated hanke deletion

---

src/domain/hanke/accessRights/AccessRightsView.module.scss
src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Added button for each user in the list to send invitation link to that user again if that user has not been identified in Haitaton before.
When the button is pressed it is disabled and it's text is changed to Kutsulinkki lähetetty until the user visits the page again.
1. Navigate to Käyttöoikeuksien hallinta view for hanke that has users that haven't been identified yet.
2. Click "Lähetä kutsulinkki uudelleen" button for some user.
3. Check that success notification is shown and that the button is disabled and button text is changed to "Kutsulinkki lähetetty".
4. Navigate away and back to the view again and check that the button you pressed previously is enabled.
other info that the tester/user …

HAI-1512 Implement sending invitation links again in user rights view

---

src/domain/johtoselvitys/Contacts.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx

If there were validation errors when user pressed Fill with own information button, those errors remained even when they should not.
1. Edit for example customer contacts name field and leave it empty
2. Click some other field. There should be validation error: "Kenttä on pakollinen".
3. Click "Täytä omilla tiedoilla" button.
4. Validation error(s) should go away from that customer contact.   

HAI-1939 Fix problem where validation errors would remain when filling sub-contacts in cable report application

---

src/common/components/footer/Footer.tsx

Update copyright footer to adhere to OSM licence:
- © Helsingin kaupunki, OpenStreetMap contributors 2023 
Deploy the application. Verify the copyright info in footer element is correct.

HAI-1736 Update copyright footer to adhere to OSM licence

---

src/common/components/textInput/TextInput.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormPerustiedot.tsx

Haitaton backend has a limit for hanke name (100 characters). Include this limit in the frontend.
Fill name for hanke, name field should not accept more than 100 characters.

HAI-1866 Add length limit for hanke name

---

cypress/integration/E2E.spec.ts
cypress/utils/indexValidator.ts
src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/hankeIndexes/HankeIndexes.test.tsx
src/domain/hanke/hankeIndexes/HankeIndexes.tsx
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/mocks/data/hankkeet-data.ts
src/domain/mocks/hankeIndexData.ts
src/domain/types/hanke.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Instead of just one joukkoliikenneindeksi show separate indexes for bus and tram.
1. Create new hanke and fill first two pages of hanke form so that it has hanke areas defined.
2. Go to third page of the form.
3. Third page of hanke form should show hanke indexes and there should be separate indexes for tram and bus.
4. Those same indexes should also be displayed in hanke page.

HAI-1879 Show separate bus and tram indexes

---

.eslintrc.js
package.json
src/common/components/radiobutton/BooleanRadioButton.tsx
src/common/components/textArea/TextArea.tsx
src/domain/forms/components/Contact.tsx
src/domain/forms/utils.ts
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/validationSchema.ts
yarn.lock

When triggering form validations, field paths in the array given to react-hook-form trigger function were not in correct order, and so focus went to wrong field when there were errors. Fixed this by making sure the field paths are in correct order.
1. Create new cable report application and fill first and second page.
2. In third page try to move to next or previous page of the form without filling any fields.
3. Focus should go to name field of the Applicant 

HAI-1921 Fix incorrect focus order of fields with error in cable report application form

---

src/domain/hanke/hankeUsers/UserRightsCheck.test.tsx
src/domain/hanke/hankeUsers/UserRightsCheck.tsx

Fixed a problem where application edit and delete buttons would not be displayed in application view when access rights feature was disabled. Made it so that when the feature is disabled, buttons are rendered without checking for user permissions.

HAI-2083 Fix application edit and delete buttons not displayed

---

src/domain/hanke/hankeUsers/UserRightsCheck.test.tsx
src/domain/hanke/hankeUsers/UserRightsCheck.tsx

Fixed a problem where application edit and delete buttons would not be displayed in application view when access rights feature was disabled. Made it so that when the feature is disabled, buttons are rendered without checking for user permissions.

HAI-2083 Fix application edit and delete buttons not displayed (#400)

---

src/common/components/textInput/TextInput.tsx
src/common/hooks/useFieldArrayWithStateUpdate.ts
src/domain/forms/components/Contact.tsx
src/domain/hanke/edit/HankeFormAlueet.tsx
src/domain/hanke/edit/components/AreaSummary.tsx
src/domain/hanke/edit/components/Haitat.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/utils.test.ts
src/domain/hanke/edit/utils.ts
src/domain/hanke/hankeIndexes/CompressedAreaIndex.tsx
src/domain/hanke/hankeView/HankeView.tsx
src/domain/types/hanke.ts

Added text input for hanke area tab in areas page of hanke form, which allows user to enter name for each hanke area.
Name input has a default value that is Hankealue + the next running number of the default names of other hanke areas. For example if there are names Hankealue 1, Hankealue 2 and Hankealue 4, the next default name would be Hankealue 5. User can then edit the default name if they want to.
1. Create new hanke and fill the first page
2. Go to the second page and draw an area to the map
3. Tab for the new area should appear below and it should have a name "Hankealue 1"
4. Edit the name to be something else
5. Changes should reflect to the tab name also
6. Draw a new area --> it should get the name "Hankealue 1"
7. Draw two new areas --> they should be named "Hankealue 2" and …

HAI-2008 Allow user to name hanke areas

---

README.md
package.json
src/domain/hanke/edit/utils.test.ts
src/domain/hanke/edit/utils.ts

Exclude `feature` field from hanke data `alueet[n]`.
PLUS: Made pre-push hook to be conditional on `WSL=true` and add `--runInBand` for Jest tests if it is set. 
Create a new Hanke (can be done locally in just ui with `yarn start-msw`), add some geometry on it, check the API call UI makes when saving or changing view to a different page. There should not be `feature` field any more.
or other location: README.md

HAI-1508: Remove feature object from API calls

---

src/common/components/fileUpload/FileUpload.module.scss
src/common/components/fileUpload/FileUpload.test.tsx
src/common/components/fileUpload/FileUpload.tsx
src/common/components/fileUpload/utils.ts
src/common/types/attachment.ts
src/domain/application/attachments.test.ts
src/domain/application/attachments.ts
src/domain/application/types/application.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/mocks/handlers.ts
src/locales/fi.json
src/testUtils/render.tsx

File upload component uses HDS FileInput internally to handle user adding files from their machine and immediately sends added files to backend and shows a loading spinner and loading text while upload is in process.
Listing of files and deleting them as well as displaying error messages are done in separate tasks.
Only way to manually test this is to replace FileInput component locally in src/domain/johtoselvitys/Attachments.tsx with this new component, for example:
```
function handleFileUpload(uploading: boolean) {
if (!uploading) {
queryClient.invalidateQueries('attachments');
}
}
<FileUpload
id="cable-report-file-upload"
accept=".pdf,.jpg,.jpeg,.png,.dgn,.dwg,.docx,.txt,.gt"
maxSize={104857600}
dragAndDrop
multiple
existingAttachments={existingAttachments}
uploadFunction={(file) => …
```

HAI-2065 Implement file upload component

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/hanke/accessRights/AccessRightsViewContainer.tsx
src/domain/hanke/hankeUsers/UserRightsCheck.test.tsx
src/domain/hanke/hankeUsers/UserRightsCheck.tsx
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/hanke/hankeUsers/hooks/useUserRightsForHanke.ts
src/domain/hanke/hankeView/HankeView.tsx
src/domain/hanke/hankeView/HankeViewContainer.tsx
src/domain/hanke/portfolio/HankePortfolio.test.tsx
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/hanke/portfolio/HankePortfolioContainer.tsx
src/domain/mocks/signedInUser.ts

Add a functionality to fecth users permissions for all related hanke. This is used in hanke portfolio listing to prevent multiple whoami http calls
Login to haitaton and view your own projects (hanke list). There should be no whoami calls, instead a single hankkeet/my-permissions call should be made. Hanke permissions should be set correctly based on what privileges you have. Note: this is only for the hanke listing page.

HAI-2041 Fetch current users permissions in a single request

---

src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/edit/HankeFormPerustiedot.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/edit/components/Haitat.tsx
src/domain/hanke/edit/hankeSchema.ts

Only hanke name is required for saving a hanke.
Additional, do not allow proceeding if hanke name is not set on the first step of the form.
Filling out a draft hanke:
- Hanke name is marked mandatory.
- A contact person is mandatory for every added contact.
Everything else is optional.

HAI-2089 Remove information requirements on hanke form

---

src/common/components/fileUpload/FileUpload.test.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Remove hanke perustaja from basic information summary, which is used in summaries and hanke page. This was actually done as a part of HAI-1400.
This commit just removes the related translations.
There should be no hanke perustaja information in hanke summary or in hanke page.

HAI-2077 Remove hanke perustaja

---

src/domain/forms/components/Contact.tsx
src/domain/hanke/edit/HankeForm.test.tsx

Hanke owner should have only one contact person by default.
Create a new Hanke, open Yhteystiedot (after filling previous sections), when adding a new owner there should be only one contact person for it.

HAI-2071 Only one contact person for owner

---

src/domain/hanke/edit/utils.ts

Sonarcloud has been reporting abot a potential problem with the regex `/\d+$/`. This can be avoided by using a capture group.
Use a capture group to find the number of the area, if the area name is a default name. Both matching and finding the number can be done with the same regex. This also removes the need to have a separate filtering step.

HAI Fix regex warning

---

src/domain/auth/components/OidcCallback.test.tsx
src/locales/i18n.ts

There was a problem in links back to homepage in login error page that user is directed to after failed login. Links had href /login instead of /fi, /sv or /en based on language, which was caused by language being set to 'login'. Fixed that by defining supportedLngs in i18n init options.
1. Change REACT_APP_OIDC_CLIENT_ID from 'haitaton-admin-ui-dev' to 'haitaton-ui-dev' in .env to use Suomi.fi login
2. Click 'Log in' in the top bar
3. Cancel the login in Suomi.fi
4. Link to front page in the Haitaton error page should take you to Haitaton front page

HAI-2060 Fix homepage links in login error page

---

src/common/components/fileDownloadList/FileDownloadList.tsx
src/domain/application/components/AttachmentSummary.tsx
src/domain/hanke/edit/components/AttachmentSummary.tsx
src/domain/hanke/hooks/useNavigateToApplicationList.ts
src/domain/hanke/portfolio/HankePortfolio.test.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx

HAI-2098 Change application attachments to use new download component
Use new file download component and also provide attachments as downloadable in application summary.
Additional: Fix bug in useNavigationToApplicationList which led to wrong initially open tab.
1. Add attachment(s) for johtoselvitys
2. Verify from summary page that the files can be downloaded and are correct files.

HAI-2098 Change application attachments to use new download component

---

src/domain/hanke/portfolio/HankePortfolio.test.tsx
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/locales/fi.json

HAI-1495 Replace textinput with searchinput in omat hankkeet. 
This is done to match the figma design.
Go to omat hankkeet. Verify that the implementation matches figma. Verify that the search filtering works.

HAI-1495 Replace textinput with searchinput in omat hankkeet

---

src/common/components/header/Header.test.tsx
src/common/components/header/Header.tsx

Top bar was missing a link to cable report application form so added it there.
Check that "Tee johtoselvityshakemus" link is in top bar and that it takes you to cable report application form.

HAI-1787 Add cable report application link to top bar

---

src/common/components/mainHeading/MainHeading.tsx
src/common/components/scrollToTop/ScrollToTop.test.tsx
src/common/components/scrollToTop/ScrollToTop.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/forms/MultipageForm.tsx
src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/hanke/hankeView/HankeView.tsx
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/homepage/HomepageComponent.tsx
src/domain/mapAndList/MapAndListContainer.tsx
src/pages/staticPages/AccessibilityPage.tsx
src/pages/staticPages/InfoPage.tsx
src/pages/staticPages/ManualPage.tsx
src/pages/staticPages/PrivacyPolicyPage.tsx
src/pages/staticPages/ReferencesPage.tsx

Focus was not set to top of the page when navigating to a different page. Fixed that by setting the focus to empty div on top of the page so that pressing tab sets the focus to Skip to main content link. Also added aria-live regions to main page headings.
When navigating to a new page press tab and check that focus is in "Siirry pääsisältöön" link.

HAI-1811 Fix focus on page change

---

Dockerfile
Dockerfile-local
nginx/nginx.conf
scripts/nginx-env.sh

Add a Content-Security-Policy header to the nginx configuration. The header tells the browser where it should download content from. This is added security for exploits like XSS.
When building the docker image, copy nginx.conf under /opt. When the container is started, run a script at startup that substitutes the environment variables and copies nging.conf to /etc/nginx/nginx.conf. The script only substitutes the environment variables specified in the script so it won't overwrite nginx variables.
Also, modify the docker file for building UI images for the local Docker Compose environment. Copy the files to the builder image selectively, so only changes in those files invalidate Docker's cache. Separate `yarn install` from `yarn build`, so that only changes in package.json or yarn.lock …

HAI-1776 Add Content-Security-Policy header

---

Dockerfile
Dockerfile-local
nginx/nginx.conf
scripts/nginx-env.sh

Add a mod to nginx that allows the removal of the Server header from HTTP responses.
In local development Docker Compose, the header is re-added by the haitaton-nginx proxy, so this can't be tested locally. I just deployed this to dev and test, so it's verifiable there until there's a new deployment.

HAI-1777 Remove version info from server header

---

cypress/integration/E2E.spec.ts
src/domain/forms/components/Contact.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/johtoselvitys/Contacts.tsx
src/domain/types/hanke.ts

- owner section is initially open and that owner have initially one contact person
- constructor, implementor and other have initially no contacts (or contact persons)
- all contacts and contact persons can be removed - except for owner which has to have one contact and contact person
- if there are constructor, implementor or other types of contacts, that section should be open by default (owner section is open because it has at least one contact which has at least one contact person)
- contact type can have empty value without validation error message
- contact person can have empty data without validation error messages
- contact person fields have no asterisk (*) marking them mandatory
Create a new or open an existing Hanke. See that contacts and contact persons behave as described …

HAI-2091 Contact person fixes

---

src/domain/hanke/edit/components/HankeGeneratedStateNotification.tsx
src/domain/hanke/hankeView/HankeView.module.scss
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/hanke/hankeView/HankeView.tsx
src/domain/hanke/portfolio/HankePortfolio.module.scss
src/domain/hanke/portfolio/HankePortfolio.test.tsx
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/mocks/data/hankkeet-data.ts
src/domain/mocks/handlers.ts
src/domain/types/hanke.ts
src/locales/fi.json

Add generated notification for generated hanke in hanke listing and hanke view.
1. Create johtoselvitys
2. In hanke listing, check that the generated hanke based on your application has the correct notification.
3. The notification should also be on that hanke's view.

HAI-1974 Add generated notification for generated hanke

---

src/domain/hanke/portfolio/HankePortfolio.module.scss
src/domain/hanke/portfolio/HankePortfolioComponent.tsx

In manual testing it was found that font size of new hanke link is too small in empty hanke list text so fixed that.

HAI-1880 Fix new hanke link font size being too small in empty hanke list text

---

src/common/components/header/Header.test.tsx
src/common/components/header/Header.tsx
src/common/hooks/useLocalizedRoutes.ts

There was a problem when user was in a route containing dynamic path segment such as application id and changed UI language. In such case user was taken to front page instead of staying in the same page.
Problem was caused because for example key with value of 'hakemus/4' was not found in language files, so fixed this by replacing the id with ':id', so in this case 'hakemus/:id, and then placing the actual id back when navigating to changed language route.
Go to some hanke page or hanke form of some previously created hanke and change language. You should remain in the same page with the language updated. Try the same also with cable report application.
other info that the tester/user needs to …

HAI-2145 Fix changing language redirecting user to front page

---

src/common/utils/date.ts
src/domain/hanke/edit/HankeFormAlueet.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/utils.ts
src/domain/types/hanke.ts

When leaving area start and end dates empty without even touching them, there would be invalid type validation error. Fixed that by setting null as default value and allowing null in validation.
1. Add new area in hanke form areas page and go to next page and return to areas page
2. There should not be validation errors in date inputs

HAI-1400 Fix validation of empty area start and end dates

---

src/domain/hanke/portfolio/HankePortfolio.test.tsx
src/domain/hanke/portfolio/HankePortfolioContainer.tsx

If fetch of hankkeet in hanke list fails for some reason, for example backend is down, show error notification to user.

HAI-1957 Show error notification to user if loading hankkeet in hanke list fails

---

src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/mocks/data/hankkeet-data.ts
src/domain/types/hanke.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Fixed naming of "Hindrance affecting lane length" choices.
Create a new Hanke or open an existing one, go to section 2 ("Alueet") and add a new area or check an existing area. The choices in "Kaistahaittojen pituus" should have correct values instead of value keys:
```
Ei vaikuta
Alle 10 m
10-99 m
100-499 m
500 m tai enemmän
```

HAI-2234 bug fix for "Hindrance affecting lane length"

---

src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormLiitteet.tsx

Modify allowed hanke attachment types according to specification.
Create hanke, add attachments to hanke: 
1. some pdf file to see that the existing allowed attachments work.
2. txt file to see that the new supported types work.
You can also test other types as well. See Jira ticket for allowed types.

HAI-2182 Modify allowed hanke attachment types

---

package.json
src/common/components/grid/ResponsiveGrid.module.scss
src/common/components/grid/ResponsiveGrid.tsx
src/common/components/transition/Transition.tsx
src/domain/forms/components/FormContact.module.scss
src/domain/forms/components/FormContact.tsx
src/domain/forms/components/NewContactPersonForm.module.scss
src/domain/forms/components/NewContactPersonForm.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/types.ts
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/map/HankeMap.test.tsx
src/domain/mocks/data/hankkeet.ts
src/domain/mocks/data/users-data.json
src/domain/mocks/data/users.ts
src/domain/mocks/handlers.ts
src/locales/fi.json
yarn.lock

User can create new user for hanke in hanke form by clicking Add new contact button and filling the form that is opened.
User that is created is not yet added as a contact person for the contact that it's created, that will be done later.
1. Create new hanke or edit existing hanke
2. Go to contacts page of hanke form
3. Click "Lisää uusi yhteyshenkilö" button for example for hanke owner
4. Form for new contact person should open below
5. Leave some of the fields empty and click "Tallenna ja lisää yhteyshenkilö" button
6. Validation errors should be shown for empty fields and new contact person should not be saved
7. Fill rest of the fields and click "Tallenna ja lisää yhteyshenkilö" button
8. Contact person form should be closed and notification "Yhteyshenkilö tallennettu" should be shown …

HAI-2160 Create new user in hanke form

---

src/domain/hanke/portfolio/HankePortfolio.test.tsx
src/domain/hanke/portfolio/HankePortfolioComponent.tsx

Design for hanke draft state notification in hanke list changed from longer notification text to a tag, so updated UI to match that.
1. Create a new hanke but don't fill all the information
2. Go to hanke list and check that hanke draft state matches Figma design: https://www.figma.com/file/dRtEnlMJUwz0KUPqAaTzq3/Haitaton-2.0?type=design&node-id=4724-24509&mode=design

HAI-1975 Update hanke draft state notification to match new design in hanke list

---

src/domain/hanke/hankeCreateDialog/HankeCreateDialog.tsx
src/domain/homepage/Homepage.test.tsx
src/domain/map/HankeMap.test.tsx

User email from profile should be pre-filled in hanke create dialog, so fixed that.
Click "Luo uusi hanke" link and check in the dialog that email is pre-filled.

HAI-2153 Fix user email not being pre-filled in hanke create dialog

---

src/assets/styles/reset.css
src/domain/hanke/accessRights/AccessRightsView.module.scss
src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/hanke/accessRights/UserCard.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/johtoselvitys/Contacts.test.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/mocks/data/users-data.json
src/domain/mocks/data/users.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Changed page heading.
Changed navigation back to hanke page to use HDS Breadcrumb component.
Added icons before users name based on their status.
Added phone number column to table.
Changed permission dropdown to plain text.
Moved invitation send button behind menu that is opened by clicking three dots icon button.
Removed Save button that would save changes to user permission as all modifications to user info are going to be in user edit page.

HAI-2158 Rework user management page

---

src/common/components/dropdown/DropdownMultiselect.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormPerustiedot.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/edit/components/ContactsSummary.tsx
src/domain/hanke/edit/types.ts
src/domain/hanke/edit/utils.ts
src/domain/hanke/hankeUsers/ContactPersonSelect.tsx
src/domain/hanke/hankeUsers/utils.ts
src/domain/map/components/HankeSidebar/HankeSidebar.module.scss
src/domain/types/hanke.ts
src/locales/fi.json

Added comboboxes to contacts page in hanke form to select existing hanke users as contact persons (yhteyshenkilöt) for hanke contacts. Creating new hanke user also adds that user as a contact person.
1. Create new hanke or edit existing hanke
2. Go to contacts page
3. Add yhteyshenkilö to hanke owner from dropdown
4. Create new yhteyshenkilö for hanke owner and check that it is added as yhteyshenkilö
5. Go to summary page
6. Check that hanke is saved successfully and that yhteyshenkilöt are shown in summary page

HAI-2165 Make it possible to select hanke users as contacts persons in hanke form

---

src/domain/auth/authService.test.ts
src/domain/auth/authService.ts
src/domain/auth/profiiliApi.ts
src/domain/auth/types.ts
src/domain/mocks/handlers.ts

The name shown in the header is retrieved from backend from new `/profiili/verified-name` endpoint.
The new endpoint is now in dev and could be used for testing. In UI tests and with `yarn start-msw` there is now always "Testi Testinen" as the name no matter what user is used in log-in.

HAI-2247 Retrieve verified name from backend

---

src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/hanke/hankeUsers/EditUserView.test.tsx
src/domain/hanke/hankeUsers/EditUserView.tsx
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/hanke/hankeUsers/hooks/useHankeUsers.ts
src/domain/hanke/hankeUsers/utils.ts
src/domain/mocks/data/users.ts
src/domain/mocks/handlers.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Implemented editing users own contact information. Fields that can be edited are email and phone number. Success notification is shown if editing is successful and user is redirected to user management view. Error notification is shown if something goes wrong.
1. Go to edit your own information from the user management page
2. Edit both the email and the phone number and press "Tallenna muutokset" button
3. You should be taken back to user management page and there should be success notification
4. Check that the information in the table is updated

HAI-2224 Make it possible for user to edit their own information

---

src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/locales/fi.json

For better accessibility, added aria-label, aria-controls and aria-expanded attributes for hanke card expand button.

HAI-1808 Add aria attributes for hanke list button, which expands the hanke card

---

package.json
yarn.lock

Redux Thunk is included as part of Redux Toolkit from version 2.0, so removed Redux Thunk from dependencies.

Remove redux-thunk from dependencies as it is included in redux toolkit 2.0

---

src/domain/hanke/edit/types.ts
src/domain/hanke/hankeUsers/EditUserView.test.tsx
src/domain/hanke/hankeUsers/EditUserView.tsx
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/mocks/data/users.ts
src/domain/mocks/handlers.ts

Implemented editing users contact information. For user who is not identified, all fields can be edited, including changing permission. For identified user first name and last name cannot be edited.
1. Go to edit unidentified users information
2. Make changes to all fields including changing permission and save
3. Check that success notification is shown and that updated information is shown in the list
4. Go to edit identified user and check that first name and last name are readonly fields

HAI-2226 User can edit other users information

---

src/domain/forms/components/testUtils.ts
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/johtoselvitys_new/Contacts.test.tsx
src/domain/johtoselvitys_new/Contacts.tsx
src/domain/johtoselvitys_new/JohtoselvitysContainer.tsx
src/domain/johtoselvitys_new/JohtoselvitysForm.test.tsx

User can create new user for hanke in johtoselvitys form by clicking Add new contact button and filling the form that is opened.
User that is created is not yet added as a contact person for the contact that it's created, that will be done later.
1. Create new johtoselvitys
2. Fill first two pages so that you get to contacts page
3. Click "Lisää uusi yhteyshenkilö" button for example for applicant and fill the information for new user and click "Tallenna ja lisää yhteyshenkilö" button
4. Success notification should be shown
5. Navigate to user management page of the hanke and check that the new person is there

HAI-2230 Create new user in johtoselvitys form

---

src/common/hooks/useFieldArrayWithStateUpdate.ts
src/common/hooks/useSelectableTabs.ts
src/domain/forms/components/Contact.tsx
src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/edit/HankeFormAlueet.tsx
src/domain/hanke/edit/utils.ts
src/domain/johtoselvitys/Geometries.tsx
src/domain/johtoselvitys_new/Geometries.tsx
src/domain/map/components/HankeDrawer/HankeDrawer.tsx

Previously geometry ids of hanke areas were not send to backend, which lead to backend creating the geometries again each time.
Now ids are sent along with other data. Also when creating new areas and saving form, hanke area data from response is set to form state.

HAI-2347 Send geometry id of hanke area when saving hanke form

---

src/common/components/map/layers/VectorLayer.tsx
src/common/components/map/modules/draw/DrawInteraction.tsx
src/domain/common/utils/liikennehaittaindeksi.test.ts
src/domain/common/utils/liikennehaittaindeksi.ts
src/domain/johtoselvitys_new/Geometries.tsx
src/domain/johtoselvitys_new/JohtoselvitysContainer.tsx
src/domain/map/HankeMap.tsx
src/domain/map/components/Layers/HankeLayer.tsx
src/domain/map/hooks/useHankeFeatures.ts
src/domain/map/utils/geometryStyle.ts
src/domain/mocks/data/hankkeet-data.ts

Show hanke areas in johtoselvitys form areas page if they exist. By default they are shown. Functionality to control what layers are displayed will be implemented later.
1. Create new johtoselvitys for hanke which has hanke areas
2. Fill first page of johtoselvitys form and go to second page
3. Check that hanke areas are displayed on map

HAI-2341 Show hanke areas in johtoselvitys form

---

src/common/components/header/Header.tsx
src/domain/application/types/application.ts
src/domain/application/utils.ts
src/domain/forms/components/OwnInformationFields.tsx
src/domain/hanke/edit/HankeFormPerustiedot.tsx
src/domain/hanke/hankeCreateDialog/HankeCreateDialog.tsx
src/domain/homepage/Homepage.test.tsx
src/domain/homepage/HomepageComponent.tsx
src/domain/johtoselvitys_new/johtoselvitysCreateDialog/JohtoselvitysCreateDialog.tsx
src/domain/johtoselvitys_new/validationSchema.ts
src/domain/mocks/data/defaultJohtoselvitysData.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Separate johtoselvitys without hanke being created first is done by opening a modal dialog and entering users phone number and work name. Email is pre-filled but can be edited. Creating johtoselvitys then works in similar way as creating hanke.
1. Use `yarn start-msw` to use API mock as the backend for this is not yet implemented
2. Check that the dialog can be opened by clicking "Tee johtoselvityshakemus" linkbox in home page, "Tee johtoselvityshakemus" link in top bar or "täytä hakemus" link in the first page of hanke form
3. Fill the form in the dialog and click "Luo hakemus" button
4. You should end up in johtoselvitys form where the work name is filled
other info that the tester/user needs …

HAI-2274 Create separate johtoselvitys from modal dialog

---

src/domain/johtoselvitys_new/Geometries.test.tsx
src/domain/map/components/Layers/HankeLayer.tsx

Fixed issue where hanke areas were not being visible if work start and end dates are set on hanke end date.
1. Create new johtoselvitys for hanke which has hanke areas
2. Fill first page of johtoselvitys form and go to second page
3. Set work start and end dates to hanke end date
4. Check that hanke areas are displayed on map

HAI-2341 Fix hanke areas not being visible if work start and end dates are on hanke end date

---

src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/hankeUsers/EditUserView.test.tsx
src/domain/hanke/hankeUsers/EditUserView.tsx
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/mocks/data/users-data.json
src/domain/mocks/data/users.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Added tooltips for user management view icons which indicate if user has been identified, if invitation has been sent or if it is users own information.

HAI-2371 Add tooltips for icons in user management view

---

src/domain/forms/hooks/useValidationErrors.ts
src/domain/hanke/edit/components/HankeDraftStateNotification.tsx
src/domain/hanke/edit/hankePublicSchema.ts
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/mocks/data/hankkeet-data.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

When hanke is in draft state, list of hanke form pages with missing information is shown in hanke view.
1. Create new hanke and go to its page
2. There should be a notification that hanke in draft state with page names that have missing information (should show 'Perustiedot', 'Alueet' and 'Yhteystiedot'
3. Edit hanke and fill perustiedot page
4. Go back to hanke page and check that 'Alueet' and 'Yhteystiedot' are only shown with missing information
5. Edit hanke and fill alueet and yhteystiedot pages
6. Go back to hanke page and check that draft state notification is not shown

HAI-1989 Show list of hanke form pages with missing information in hanke view

---

src/common/components/dropdown/Dropdown.tsx
src/common/components/dropdown/DropdownMultiselect.tsx
src/common/components/textInput/TextInput.tsx
src/domain/application/components/BasicInformationSummary.tsx
src/domain/application/types/application.ts
src/domain/application/utils.ts
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/hankeUsers/ContactPersonSelect.tsx
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/hanke/hankeUsers/hooks/useHankeUsers.ts
src/domain/johtoselvitys/Contacts.test.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys_new/Contacts.tsx
src/domain/johtoselvitys_new/JohtoselvitysContainer.tsx
src/domain/johtoselvitys_new/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys_new/utils.ts
src/domain/johtoselvitys_new/validationSchema.ts
src/domain/mocks/data/defaultJohtoselvitysData.ts
src/domain/mocks/data/hakemukset-data.ts
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts

Added comboboxes to contacts page in johtoselvitys form to select existing hanke users as yhteyshenkilo for hakemus yhteystieto. Creating new user also adds that user as yhteyshenkilo.
Also made a change that johtoselvitys PUT request only sends applicationData instead of the whole hakemus data.
1. Create new johtoselvitys
2. Fill information for first two pages and go to contacts page
3. Add yhteyshenkilö for hakija and työn suorittaja
4. Create new yhteyshenkilö for hakija and check that it is added as yhteyshenkilö
5. Go to summary page
6. Check that johtoselvitys is saved successfully and that yhteyshenkilöt are shown in summary page

HAI-2254 Make it possible to select hanke users as yhteyshenkilo for yhteystieto in johtoselvitys form

---

src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/hanke/hankeUsers/EditUserView.test.tsx
src/domain/hanke/hankeUsers/EditUserView.tsx
src/domain/hanke/hankeUsers/UserDeleteDialog.tsx
src/domain/hanke/hankeUsers/UserDeleteInfoErrorNotification.tsx
src/domain/hanke/hankeUsers/UserDeleteNotification.tsx
src/domain/hanke/hankeUsers/hankeUser.ts
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/hanke/hankeUsers/hooks/useDeleteInfo.ts
src/domain/hanke/hankeUsers/hooks/useUserDelete.tsx
src/domain/hanke/hankeUsers/utils.ts
src/domain/mocks/data/users-data.json
src/domain/mocks/data/users.ts
src/domain/mocks/handlers.ts
src/locales/fi.json
src/testUtils/render.tsx

Added delete buttons to user management view and user edit view.
When clicking the delete button, it is checked from backend if user can be deleted. User who has active hakemuksia or who is the only yhteyshenkilö of omistaja cannot be deleted. Dialog showing the delete information is opened and if user can be deleted there are buttons for confirming and cancelling. Clicking the confirm button deletes the user and a notification is shown.
Currently as creating johtoselvitys is broken, the best way for testing different scenarios is to use `yarn start-msw` to use mocking (getting delete info for first few users of HAI22-2 hanke return info for different scenarios). Real backend can be used to test at least deleting user who has no hakemuksia.
Please describe here if there …

HAI-2391 Implement hanke user delete

---

src/domain/application/utils.ts
src/domain/johtoselvitys_new/JohtoselvitysContainer.tsx
src/domain/johtoselvitys_new/JohtoselvitysForm.test.tsx
src/domain/mocks/data/users.ts
src/domain/mocks/handlers.ts

Show Send button only if the user is one of the contact persons and use new API for sending.
With `yarn start-msw` this can be tested by creating a new Johtoselvityshakemus. If you do not add yourself (Testi Testinen) as a contact person the Send button is not shown.

HAI-2302 Show Send button only if the user is one of the contact persons and use new API for sending

---

src/domain/johtoselvitys_new/Contacts.tsx
src/locales/fi.json

Added new instruction text in Yhteystiedot section
Create new Johtoselvityshakemus and fill it up until 3/5 Yhteystiedot. There should be new instruction text same as in Figma.

HAI-2435 Added new instruction text in Yhteystiedot section

---

src/domain/hanke/edit/HankeFormAlueet.tsx
src/domain/johtoselvitys/Geometries.tsx
src/domain/johtoselvitys_new/Geometries.tsx
src/locales/fi.json

Added new instruction text in area sections in both Hanke and Johtoselvityshakemus.
Create a new Hanke and see that the new text is shown in areas section. Same goes for Johtoselvityshakemus.

HAI-2444 Added new instruction text in area sections

---

src/common/components/dropdown/DropdownMultiselect.tsx
src/domain/hanke/edit/HankeFormPerustiedot.tsx
src/domain/johtoselvitys_new/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys_new/validationSchema.ts
src/locales/fi.json

If there are no yhteyshenkilöt, error is displayed below dropdown.
1. Create new johtoselvitys and fill first two pages so that you get to contacts page
2. Try to move to next page
3. Along with other validation errors, there should be error "Vähintään yksi yhteyshenkilö tulee olla asetettuna" below "Yhteyshenkilöt" dropdowns
4. Add yhteyshenkilö and move focus away from the field
5. Error should disappear

HAI-2439 Add validation that johtoselvitys yhteystieto must have at least one yhteyshenkilö

---

src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/hanke/hankeView/HankeView.tsx

"Käyttäjähallinta" button does not depend on hanke feature but only on user management feature.
Disable `REACT_APP_FEATURE_HANKE` and keep `REACT_APP_FEATURE_ACCESS_RIGHTS` enabled. The button should still be visible and user management available.

HAI-2460 Show user management button if the feature is enabled

---

src/domain/hanke/accessRights/AccessRightsInfo.tsx
src/domain/hanke/hankeUsers/EditUserView.test.tsx
src/domain/hanke/hankeUsers/EditUserView.tsx

Hanke-related access rights are not shown or selectable in user management if the hanke feature is not enabled.
Enabled and disable hanke feature in UI and see that the selections for access rights are according to the specs.

HAI-2451 Hide hanke-related access rights

---

src/domain/forms/MultipageForm.tsx
src/domain/forms/formStepReducer.ts
src/domain/forms/hooks/useValidationErrors.ts
src/domain/forms/types.ts
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/edit/components/MissingFieldsNotification.tsx
src/domain/hanke/edit/hankePublicSchema.ts
src/locales/fi.json

Notification is updated when user fills fields and disappears when all required fields have been filled. Is summary page there is notification about what pages have missing information.
1. Create new hanke
2. Check in perustiedot, alueet and yhteystiedot page that missing fields are shown in notification on top of the form and that they and the notification disappear from each page as the required fields are filled.

HAI-2406 Show notification with missing fields required for public hanke in each page of hanke form

---

src/common/components/app/theme.ts
src/common/components/dropdown/DropdownMultiselect.tsx
src/domain/forms/components/NewContactPersonForm.module.scss
src/domain/forms/components/NewContactPersonForm.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/hankeUsers/ContactPersonSelect.tsx
src/domain/johtoselvitys_new/Contacts.tsx
src/locales/fi.json

Added assistive text and placeholder for yhteyshenkilö dropdown in hanke form and johtoselvitys form.
Added tooltip for yhteyshenkilö dropdown in johtoselvitys form.
Added info notification for new yhteyshenkilö form.
Check that UI matches design: https://www.figma.com/file/CSWoUcI2jslxfOgBYgjKuK/Haitaton-HDS-3.0.0?type=design&node-id=449-9560&mode=design&t=9Inj1EXiHxKyzUaL-4

HAI-2442 Add assistive text and placeholder for yhteyshenkilö dropdown

---

Dockerfile
Dockerfile-local

Use Nginx 1.22.1 Docker image since that is the version nginx-extras need and nginx:stable has just been upgraded to 1.26.0-1~bookworm which breaks Docker build

Use Nginx 1.22.1 Docker image

---

Dockerfile-local

Builds using Dockerfile-local are failing, because eslint config files are not copied to the builder.

HAI Add eslint config to Docker Compose build

---

src/domain/johtoselvitys_new/Contacts.tsx
src/domain/johtoselvitys_new/JohtoselvitysForm.test.tsx

Fixed problem where validation error for no yhteyshenkilot being set remained when creating new yhteyshenkilo and that yhteyshenkilo is set.
1. Fill Johtoselvitys form up to Yhteyshenkilöt page
2. Add yourself as yhteyshenkilö for some role
3. Remove yourself from yhteyshenkilöt
4. There should be error "Vähintään yksi yhteyshenkilö tulee olla asetettuna"
5. Create new yhteyshenkilö for that role
6. Error should disappear

HAI-2481 Fix showing validation error when creating yhteyshenkilo in Johtoselvitys

---

src/common/components/HDSConfirmationDialog/ConfirmationDialog.tsx
src/domain/application/hooks/useNavigateToApplicationView.ts
src/domain/johtoselvitys_new/JohtoselvitysContainer.tsx
src/domain/johtoselvitys_new/JohtoselvitysForm.test.tsx
src/locales/fi.json
src/pages/EditJohtoselvitysPage.test.tsx
src/pages/EditJohtoselvitysPage.tsx

If user navigates to johtoselvitys that has been sent either by pressing back button in browser or by browser address bar, show a dialog with text that johtoselvitys has been sent and a button to navigate back to hakemus view.
1. Create new johtoselvitys from johtoselvitys create dialog
2. Fill all required information and send the application
3. Press browser back button to go back to johtoselvitys form
4. Dialog with text "Hakemus on lähetetty, eikä sitä voi enää muokata. Tarkastele hakemuksen tietoja hakemussivulla." should be shown
5. Press the "Siirry hakemussivulle" button
6. You should end up to hakemus view

HAI-2462 Fix navigating back to sent johtoselvitys

---

src/domain/johtoselvitys_new/Geometries.test.tsx
src/domain/johtoselvitys_new/Geometries.tsx

Hanke areas are not shown when editing johtoselvitys form when hanke is in generated state so that they don't confuse user.
1. Create new johtoselvitys from johtoselvitys create dialog
2. Fill information for first two pages so that there are work areas
3. Save form either by going forward or backward in the form or save and quit
4. Go to areas page and modify work area(s) to see that hanke areas of the generated hanke are not visible

HAI-2445 Fix showing hanke areas in johtoselvitys form when hanke is generated

---

src/domain/hanke/portfolio/HankePortfolioComponent.tsx

Put 'show hanke' button inside featureflags component.
Disable hanke feature by setting `REACT_APP_FEATURE_HANKE=0` and run the application. "Näytä hanke" button should not be shown in hanke list.

HAI-2546 Do not show 'show hanke' button when hanke feature is not enabled

---

src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/hanke/hankeUsers/EditUserView.test.tsx
src/domain/hanke/hankeUsers/hankeUsersApi.ts
src/domain/hanke/hankeUsers/hooks/useResendInvitation.ts
src/domain/mocks/data/users.ts
src/domain/mocks/handlers.ts

Backend returns updated user after resending invitation, so invitation sent date is updated from that response in edit user view.
1. Go to edit some hanke user
2. Press "Lähetä kutsulinkki uudelleen" button
3. Date in "Kutsulinkki Haitattomaan lähetetty" text should be updated to today

HAI-2538 Update invitation sent date after resending invitation in edit user view

---

src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/accessRights/AccessRightsView.tsx
src/locales/fi.json

In user management mobile view if there are no search results, show not found text.
1. Go to user management view of some hanke with browser window in small size
2. Type some search text that has no results
3. Text "Haulla ei löytynyt yhtään henkilöä" should be displayed

HAI-2545 Show not found text in user management mobile view if there are no search results

---

src/common/components/fileUpload/FileUpload.module.scss
src/common/components/fileUpload/FileUpload.test.tsx

No files selected notification is hidden in FileUpload component because it is not needed and can be confusing to users.
1. Check in johtoselvitys and hanke forms attachments pages that the notification "Yhtään tiedostoa ei ole valittu." is not visible.

HAI-2536 Hide no files selected notification in FileUpload component

---

src/domain/johtoselvitys_new/JohtoselvitysContainer.tsx
src/domain/johtoselvitys_new/JohtoselvitysForm.test.tsx
src/locales/fi.json

Show Send Application button always (if application is a draft) and disable it when the user is not a contact person on the application. Show a notification in this case.
1. Create new johtoselvitys and fill it
2. Add a new contact person (other than yourself)
3. Send button should be visible and disabled and a notification should be shown (under the buttons).

HAI-2544 Show Send Application button always and disable it when send is not allowed

---

src/domain/homepage/HomepageComponent.tsx

When user closes feedback for Haitaton notification in home page, set value to session storage, so that the notification is not shown again on page refresh.
1. Close the notification "Auta meitä tekemään Haitattomasta vielä parempi" in home page and refresh the page
2. Notification should not be visible

HAI-2506 Show feedback notification in home page once per session

---

src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/hankeUsers/EditUserView.test.tsx
src/domain/hanke/hankeUsers/utils.ts

Show delete button for users if they are not the only identified user with KAIKKI_OIKEUDET permission. Before the check did not count identified status.
1. Create a johtoselvityshakemus
2. Add a contact person
3. Give them KAIKKI_OIKEUDET
4. Check that you cannot remove yourself from hanke

HAI-2541 Stricter user deletion check

---

src/domain/application/components/ApplicationStatusTag.module.scss
src/domain/application/components/ApplicationStatusTag.test.tsx
src/domain/application/components/ApplicationStatusTag.tsx
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts

Fixed a problem where after sending johtoselvityshakemus to Allu, the status tag color of hakemus would not always update correctly to yellow color.
Also made sure that all different statuses have correct colors.
1. Create new johtoselvitys
2. Fill the form and send it
3. Status tag of the new hakemus should be yellow with text "Odottaa käsittelyä"

HAI-2533 Fix updating hakemus status tag color in hakemus list

---

src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/hanke/hankeView/HankeView.tsx
src/domain/hanke/portfolio/HankePortfolio.test.tsx
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/map/components/MapPlaceholder/MapPlaceholder.tsx
src/locales/fi.json

When there are no hanke areas yet, a placeholder text is shown in place of a map in hanke list and hanke view.
Check that hanke with no areas has the placeholder text in place of a map in hanke list and hanke view.

HAI-1995 Add information to hanke list and hanke view when there are no hanke areas

---

src/common/components/HDSConfirmationDialog/ConfirmationDialog.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/components/Haitat.module.scss
src/domain/hanke/edit/components/Haitat.tsx
src/locales/fi.json

Moved hanke area delete button to more visible place and added confirmation dialog for deletion.
1. Go to hanke form areas page and draw hanke area
2. Check that the area delete button placement matches Figma design: https://www.figma.com/design/CSWoUcI2jslxfOgBYgjKuK/Haitaton-HDS-3.0.0?node-id=122-12883&t=PQfH4vB3bDPUu48G-4
3. Press area delete button
4. Confirmation dialog should open
5. Confirm delete in dialog
6. Area should be removed

HAI-2475 Improve hanke area deletion

---

src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx

Added default value of Yritys for contact type dropdowns in hanke form contacts page.
Check that contact type of yhteyshenkilöt has default value of Yritys.

HAI-2406 Add default values for contact types in hanke form

---

src/common/components/header/Header.test.tsx
src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/hooks/useApplicationSendNotification.tsx
src/domain/application/utils.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/map/components/AddressSearch/AddressSearch.test.tsx
src/domain/mocks/data/hakemukset-data.ts
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/data/users.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Application can be sent in application view just like in the application form. Same rules apply to the new button in application view as in the form:
* Button is shown, if the user has right permissions
* Button is disabled, if the user is not a contact person on application
Also, changed the error notification in case of the sending fails to be error instead of alert. Also, show the info icon in the notification when the button is disabled (the user is not a contact person on application).
Additionally, cleanep up the code a bit (unused `req` parameterts renamed to `_`, not-used `testi@test.com` changed to `matti.meikalainen@test.com` which is an existing test user, removed/renamed old pre-kortisto functions etc)
* Create a new cable report application or go the application page of an …

HAI-2516 Send application button in application view

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/ApplicationViewContainer.tsx

Show user access rights on application page.
Implementation is copied from HankeView/HankeViewContainer.
Create a new or open an existing application. User access rights should be shown on the page.

HAI-2519 Show user access rights on application page

---

src/domain/hanke/hankeUsers/EditUserView.test.tsx
src/domain/hanke/hankeUsers/EditUserView.tsx

In user management page, show the user role/roles only if the user has any role in the project.
* Go to user management page for a user that has a role in the project (= the user is a contact person of any contact type Omistaja/Rakennuttaja/Toteuttaja/Muu). The role and label "Rooli hankkeessa:" should be shown.
* Do the same for a user that has no role in the project - not even the label should be shown

HAI-2522 Show user role in project only if the user has a role

---

src/common/components/inputCombobox/InputCombobox.tsx
src/domain/kaivuilmoitus/BasicInfo.tsx
src/locales/fi.json

Changed entering existing cable report identifiers and placement contracts to be case insensitive.
Added placeholder text and better helper text to cable report field.
1. Try entering cable report identifiers (for example JS0000001 and js0000002) and check that both are accepted
2. Try same for placement contracts (for example SL0000001 and sl0000002)

HAI-1367 Fixes for kaivuilmoitus form cable report and placement contract fields

---

src/common/components/app/app.scss
src/domain/mapAndList/MapAndListContainer.tsx

The tabs in Map and List Container were implemented as Buttons inside NavLink, which resulted screen reader to read both the link and the button. This changes the buttons to divs, so the screen reader works correctly.
Use VoiceOver or other screen reader software to switch between links and map views. It should work correctly.

HAI-1424: Change Buttons inside NavLink to divs for the sake of accessibility

---

src/domain/hanke/edit/components/HankeDraftStateNotification.tsx
src/domain/hanke/edit/hankePublicSchema.ts
src/domain/hanke/edit/types.ts

In hanke form summary page where all pages with missing information are listed, there was an entry tabit.ytunnus. Fixed that.
Also fixed incorrect order of pages which would occur in some cases.
1. Create new hanke
2. Visit contacts page but don't fill anything there and go to summary page
3. Pages with missing information should be listed in the notification with nothing extra

HAI-2406 Fix incorrect page name in hanke draft state notification in hanke form summary page

---

src/domain/map/components/HankeSidebar/HankeSidebar.tsx

trapFocus property was disabled for side panel, which resulted the user having to tab all through the background elements before being able to access the panel content. This change makes opening the panel to also focus on the panel contents.
Click an area on the map. The tab focus should not be inside the panel. Using VoiceOver, the user moving forward on the page will immediately access the panel contents.

HAI-1415: Trap focus to side panel for improved accessiblity

---

src/domain/common/haittaIndexes/HaittaIndex.tsx
src/domain/common/haittaIndexes/HaittaIndexNumber.tsx
src/domain/hanke/hankeIndexes/CompressedAreaIndex.tsx
src/locales/fi.json

Add tooltip that describes the scale (1–5) next to index number for accessiblity in hanke page
Go to hanke page which has an area with nuisance index. There is a tooltip next to the index number. The screen reader should read the description before the index number, and ignore the tooltip.
or other location

HAI-1411: Add tooltip next to index number for accessiblity

---

src/common/components/footer/Footer.module.scss
src/common/components/footer/Footer.tsx
src/domain/application/hooks/useNavigateToApplicationView.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/pages/EditJohtoselvitysPage.tsx

Previously when saving and quitting, user was taken to application list. Changed it so that user is taken to application view. Made the same change also when sending cable report application.
Save and quit in both johtoselvitys and kaivuilmoitus form and check that you end up in correct application view.

HAI-2521 When saving and quitting in application form navigate to application view

---

src/common/utils/yup.ts
src/domain/application/components/ApplicationContacts.tsx
src/domain/forms/components/FormContact.tsx
src/domain/forms/components/NewContactPersonForm.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/hankeUsers/EditUserView.test.tsx
src/domain/hanke/hankeUsers/EditUserView.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/locales/fi.json
src/types/yup-extensions.d.ts

In Hanke and Hakemus forms, when adding a new contact person, its email is validated against existing users and if the email is in use an error message is shown.
Also, in user management, one cannot change the user's email to be same as someone else's.
* In project or application form, add a new contact person with an existing email address. There should be an error message shown.
* In user management, try to change user's email to be the same as someone else's. There should be an error message shown.

HAI-2514 validate user email for duplicates

---

src/common/components/dropdown/DropdownMultiselect.tsx
src/domain/application/components/ApplicationContacts.tsx
src/domain/application/yupSchemas.ts
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/hankeUsers/ContactPersonSelect.tsx
src/domain/kaivuilmoitus/Contacts.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx

There was a problem in contacts page that even if filling all required fields, it would appear that there is some missing information.
Changed validation for ovt field so that empty string is also valid so there is no error if user leaves the field empty.
Also changed yhteyshenklöt fields to be required.
In kaivuilmoitus form contacts page, fill all required fields and move to next page. Stepper icon for contacts page should be completed and there should not be a warning icon.

HAI-1370 Fix validation of OVT-tunnus field in kaivuilmoitus

---

src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/edit/hankeSchema.ts
src/locales/fi.json

Marked hanke muu taho role, name and email to be required and added required validation for role to yup schema.
1. Add muu taho for hanke
2. Check that role, name and email fields are required
3. Visit role, name and email fields
4. Check that there are validation errors below the fields and also in the top notification about missing fields

HAI-2573 Fix hanke muu taho validation

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/components/ApplicationContacts.tsx
src/domain/forms/components/FormContact.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx
src/domain/hanke/hankeUsers/utils.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Move 'Add new contact person' button to be aside of the contact person dropdown list.
Also, adjusted the Send button functionality a bit in application form: after successful send the button is not enabled but the loading status is removed.
Check Hanke, Johtoselvitys and Kaivuilmoitus form for adding new contact persons. The button location should be according to Figma specification and the adding should work as before with right tooltips (on application forms only) etc.

HAI-2585 Move 'Add new contact person' button

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/hooks/useSendApplication.ts
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/homepage/Homepage.test.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/mocks/data/hakemukset-data.ts
src/domain/mocks/data/users-data.json

Added send application button to summary page of kaivuilmoitus form that is visible if all required fields are filled. Made the same change to application page send button visibility.
1. Create new kaivuilmoitus and fill all required fields
2. Check in the summary page and in the application view that the "Lähetä hakemus" button is visible (you can also check that it's not visible if some required information is missing)
3. Click the send button and check that sending is successful

HAI-2578 Make it possible to send kaivuilmoitus to Allu

---

src/domain/kaivuilmoitus/Contacts.tsx

Made a change that customer reference field is not reset when changing invoicing customer type to be Person or Other.
1. Go to contacts page of kaivuilmoitus form and fill customer reference (asiakkaan viite) for invoicing customer
2. Navigate to another page of the form
3. Go back to contacts page and check that customer reference is still there

HAI-1370 Fix for customer reference field in kaivuilmoitus form

---

src/domain/johtoselvitys/Geometries.test.tsx
src/domain/map/HankeMap.test.tsx
src/domain/map/components/Layers/HankeLayer.tsx

When setting work dates in kaivuilmoitus areas page, all hanke areas were shown if hanke start and end dates were within work dates. Changed it so that filtering is done based on hanke area dates so that only areas that are within the set dates are shown.
1. Have a hanke that has at least two areas that have no overlapping dates (for example 1.9.2024 - 2.9.2024 and 4.9.2024 - 6.9.2024)
2. Create new kaivuilmoitus and in the areas page set work dates so that not all hanke area dates are within those dates
3. Check that only hanke areas that are within the set work dates area shown

HAI-1368 Fix showing hanke areas based on work dates in kaivuilmoitus

---

Dockerfile
Dockerfile-local

The official Docker registry is declining pull requests for images because of rate limits.
As a temporary workaround, use AWS ECR images, which have a limit of one per second.

HAI Use AWS ECR Docker images

---

src/domain/common/haittaIndexes/ProcedureTips.test.tsx
src/domain/common/haittaIndexes/ProcedureTips.tsx
src/domain/common/haittaIndexes/__snapshots__/ProcedureTips.test.tsx.snap
src/domain/hanke/edit/components/Haittojenhallintasuunnitelma.tsx
src/locales/fi.json

Added procedure tips for each kulkumuoto in haittojenhallinta page. Tips are inside accordions which are initially closed.
Check in hanke haittojenhallinta page that each kulkumuoto has its toimenpidevinkit. You can also check that they match confluence: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8236367978/Asiakasryhm+luokittelut+0-5+ja+toimenpidevinkit+asiakasryhmitt+in

HAI-2380 Show procedure tips (toimenpidevinkit) in hanke form haittojenhallinta page

---

scripts/translate-common.ts
scripts/translate-excel-to-json.ts

Support new structures in localization Excel file export and import. Mainly these concern atm `hankeForm.haittojenhallintaForm.procedureTips` which has not just strings or objects (of strings or nested objects) but also numbers and arrays of strings and objects.
* run `yarn locales:export`
* check the excel file `locale_export.xlsx` - see how `hankeForm.haittojenhallintaForm.procedureTips` is structured
* adjust some missing Swedish and/or English texts under `hankeForm.haittojenhallintaForm.procedureTips` and save the Excel file
* run `yarn locales:import`
* check modifications in `sv.json` and `en.json`

Support arrays and numbers in locales excel export and import

---

src/domain/common/haittaIndexes/HaittaIndex.tsx
src/domain/common/haittaIndexes/HaittaIndexTooltip.module.scss
src/domain/common/haittaIndexes/HaittaIndexTooltip.tsx
src/domain/common/haittaIndexes/HaittaIndexes.tsx
src/domain/common/haittaIndexes/HaittaSection.tsx
src/domain/common/haittaIndexes/HaittaSubSection.tsx
src/domain/common/haittaIndexes/HaittaTooltipContent.test.tsx
src/domain/common/haittaIndexes/HaittaTooltipContent.tsx
src/domain/common/haittaIndexes/__snapshots__/HaittaTooltipContent.test.tsx.snap
src/domain/hanke/edit/components/Haittojenhallintasuunnitelma.tsx
src/domain/hanke/hankeView/HankeView.module.scss
src/domain/hanke/hankeView/HankeView.tsx
src/locales/fi.json

Added tooltips for nuisance indexes for different liikennemuodot in hanke haittojenhallinta. Also added the tooltips to hanke areas page.
Check in hanke haittojenhallinta page that nuisance index tooltips exist for each liikennemuoto and you can check that they are correct: https://helsinkisolutionoffice.atlassian.net/wiki/spaces/HAI/pages/8236367978/Asiakasryhm+luokittelut+0-5+ja+toimenpidevinkit+asiakasryhmitt+in

HAI-2384 Add tooltips for nuisance indexes in haittojenhallinta

---

src/domain/hanke/edit/components/Haittojenhallintasuunnitelma.tsx
src/domain/kaivuilmoitus/validationSchema.ts
src/domain/map/components/HankkeenHaittojenhallintasuunnitelma/HankealueMap.tsx
src/domain/map/hooks/useHankealueFeature.ts

Color of the areas in haittojenhallintasuunnitelma are based on nuisance index.
Create or open a hanke, add some areas to it and see that the area colors are correct in haittojenhallintasuunnitelma.

HAI-2465 Haittojenhallintasuunnitelma area color based on nuisance index

---

src/common/utils/yup.ts
src/domain/forms/hooks/useValidationErrors.ts
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/edit/components/Haittojenhallintasuunnitelma.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/utils.ts
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/mocks/data/hankkeet-data.ts
src/locales/fi.json
src/types/yup-extensions.d.ts

When there is no traffic nuisance detected for some traffic type in some hanke area, the nuisance control plan is not mandatory for that type.
* Create a new or open an existing hanke
* Add some areas to it with different nuisance indexes (incl. some 0 too)
* Check Haittojenhallintasuunnitelma page
* For those areas and types where nuisance index is 0, the control plan field is hidden behind a button and is not mandatory

HAI-2383 Nuisance control plan is not mandatory for undetected traffic nuisances

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/components/ApplicationList.test.tsx
src/domain/application/components/ApplicationListItem.tsx
src/domain/application/components/DecisionLink.tsx
src/domain/application/types/application.ts
src/domain/application/utils.test.ts
src/domain/application/utils.ts
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/homepage/Homepage.test.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/johtoselvitys/types.ts
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/types.ts
src/domain/mocks/data/hakemukset-data.ts
src/locales/fi.json

Add paatokset into Application (and HankkeenHakemus even though it is needed a bit later with decision history). Show download links for each current decision type in application view. Added similar code for application list view also but API does not yet provide the data for that view.
* Create some decision(s) for a kaivuilmoitus (see e.g. https://github.com/City-of-Helsinki/haitaton-backend/pull/776 and https://github.com/City-of-Helsinki/haitaton-backend/pull/777 and https://github.com/City-of-Helsinki/haitaton-backend/pull/781)
* Open the application, there should be working download links for decision(s)

HAI-2621 Decision download links

---

src/common/components/searchInput/SearchInput.module.scss
src/common/components/searchInput/SearchInput.test.tsx
src/common/components/searchInput/SearchInput.tsx
src/domain/application/components/ApplicationContacts.tsx
src/domain/hanke/hankeUsers/UserSearchInput.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx

Replaced contact name field in johtoselvitys and kaivuilmoitus form contacts page with search input to allow user to select existing hanke user as they are typing the name. Selecting existing user fills email and phone fields for that contact.
1. Create or modify existing johtoselvitys or kaivuilmoitus and go to the contacts page
2. Start typing to the name field of for example "Työstä vastaava"
3. Suggestions of existing hanke users should be displayed if their name matches the input value
4. Try selecting a suggestion
5. Email and phone should be filled for that user

HAI-2590 Change contact name field to search input in application

---

src/common/components/searchInput/SearchInput.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormYhteystiedot.tsx

Replaced contact name field in hanke form contacts page with search input to allow user to select existing hanke user as they are typing the name. Selecting existing user fills email and phone fields for that contact.
1. Create or modify existing hanke and go to the contacts page
2. Start typing to the name field of for example "Hankkeen omistaja"
3. Suggestions of existing hanke users should be displayed if their name matches the input value
4. Try selecting a suggestion
5. Email and phone should be filled for that user

HAI-2511 Change contact name field to search input in hanke form

---

src/domain/api/api.ts
src/domain/api/publicEndpoints.ts

Made a change that token is not required for /banners and /public-hankkeet endpoints which are public.

HAI-2698 Fix banners and public hankkeet for user who is not logged in

---

src/common/components/inputCombobox/InputCombobox.tsx
src/common/components/searchInput/SearchInput.tsx
src/common/components/textInput/TextInput.tsx
src/domain/application/components/ApplicationContacts.tsx
src/domain/application/yupSchemas.ts
src/domain/forms/utils.ts
src/domain/kaivuilmoitus/BasicInfo.tsx
src/domain/kaivuilmoitus/Contacts.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/validationSchema.ts
src/domain/mocks/data/hakemukset-data.ts

There was an issue that if OVT and registry key fields in kaivuilmoitus would be left empty, they would be sent as empty strings to backend, which caused errors.
Made a change that those fields are null by default and if they are clered they are set as null.
Also fixed validation of rockExcavation and cableReport fields and set registry key fields of yhteystiedot as required.
1. Create new kaivuilmoitus or edit existing
2. Fill address fields for invoicing customer (laskutustiedot), but leave "OVT-tunnus" and "Välittäjän tunnus" fields empty
3. Change page so that application is saved
4. Save should be successful and there should not be any errors from backend
other info that the tester/user …

HAI-2681 Make sure that empty OVT and registry key fields are sent as null in kaivuilmoitus

---

src/domain/application/components/ApplicationAddDialog.test.tsx
src/domain/application/components/ApplicationAddDialog.tsx
src/locales/fi.json

Changed label for new kaivuilmoitus to include text "(ja johtoselvitys)".
* Add a new application for hanke
* Check that the label is correct for kaivuilmoitus

HAI-2598 Change label for new kaivuilmoitus to include text about cable report

---

src/common/utils/yup.ts
src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/types/application.ts
src/domain/application/utils.ts
src/domain/johtoselvitys/validationSchema.ts
src/domain/kaivuilmoitus/components/ApplicationReportOperationalConditionDialog.tsx
src/domain/kaivuilmoitus/hooks/useApplicationReportOperationalConditionNotification.tsx
src/domain/kaivuilmoitus/validationSchema.ts
src/domain/mocks/data/hakemukset-data.ts
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts
src/locales/fi.json
src/types/yup-extensions.d.ts

A new button is shown on application page if the application has correct status and the user has correct permissions. When the button is clicked, a dialog is shown where the user can fill in the reporting date. When the date is given and verification button clicked, the data is sent to backend.
* Create a new kaivuilmoitus or use an existing one
* Send kaivuilmoitus to Allu
* Button "Ilmoita toiminnalliseen kuntoon" should be visible in application view
* Clicking the button open a dialog
* Enter a date (valid dates are from the beginning of application start date until today)
* "Vahvista" button should be enabled if the date is valid
* Clicking "Vahvista" calls API and closes the dialog
* If clicking "Ilmoita toiminnalliseen kuntoon" again the dialog should show the previous report dates …

HAI-2557 Report kaivuilmoitus in operational condition

---

package.json
src/common/components/map/modules/draw/DrawInteraction.tsx
src/common/components/map/modules/draw/DrawModule.tsx
src/domain/application/components/ApplicationMap.tsx
src/domain/johtoselvitys/Geometries.tsx
src/domain/kaivuilmoitus/Areas.tsx
src/domain/kaivuilmoitus/components/TyoalueTable.tsx
src/domain/map/components/Layers/HankeLayer.tsx
src/domain/map/utils/isFeatureWithinFeatures.ts
yarn.lock

In kaivuilmoitus and johtoselvitys drawing outside hanke areas is prevented. However this restriction does not apply to johtoselvitys which has generated hanke.
This is implemented by not allowing drawing to start outside of hanke areas and it also cannot be ended outside. Also modifying work areas is restricted to hanke areas. Also when drawing tool is active point geometry is not displayed when cursor is outside hanke areas to indicate that drawing is not possible.
1. Create new kaivuilmoitus or edit existing
2. When drawing new work areas check that they cannot be drawn outside hanke areas
3. Also check that work areas can't be modified so that they go outside hanke areas
other info that the …

HAI-2340 Prevent drawing work areas outside hanke areas

---

src/common/components/fileUpload/FileList.tsx
src/common/components/map/overlay/Overlay.tsx
src/common/hooks/useDebouncedMutation.test.tsx
src/common/hooks/useDebouncedMutation.ts
src/domain/application/components/ApplicationCancel.tsx
src/domain/application/components/ApplicationMap.tsx
src/domain/application/hooks/useSaveApplication.ts
src/domain/application/hooks/useSendApplication.ts
src/domain/forms/components/NewContactPersonForm.tsx
src/domain/hanke/hankeCreateDialog/HankeCreateDialog.tsx
src/domain/hanke/hankeUsers/UserDeleteDialog.tsx
src/domain/johtoselvitys/johtoselvitysCreateDialog/JohtoselvitysCreateDialog.tsx
src/domain/mocks/handlers.ts
src/index.tsx

There was a problem with adding a new contact for hanke where clicking "Tallenna ja lisää yhteyshenkilö" button multiple times would send requests and the ones after the first one would fail because the same user was already created with the first request and an error would be shown to user.
Fixed the problem by creating a wrapper for react-query useMutation hook where the mutate function is debounced, preveting multiple consecutive mutations happening in short succession.
Also applied that hook to places where there might be a risk for multiple consecutive requests.
1. Add new contact person in hanke form, johtoselvitys form or kaivuilmoitus form
2. When adding contact person try to click "Tallenna ja lisää yhteyshenkilö" button many times in a row
3. Check that only one POST request for …

HAI-2652 Prevent multiple requests happening because of multiple button clicks

---

src/domain/homepage/HomepageComponent.tsx

Fixed "Kirjaudu sisään tehdäksesi hakemus" button in homepage which is shown if PUBLIC_HANKKEET feature is disabled.
Replaced regular Button with LoginButton component which handles the redirection to the OIDC server.

HAI-2757 Fix login button not working in homepage

---

src/common/components/customAccordion/CustomAccordion.tsx
src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/__snapshots__/ApplicationView.test.tsx.snap

Work areas are found under hanke area accordions which are closed by default.
Check in kaivuilmoitus page that work areas are grouped in sidebar under hanke area accordions.

HAI-2627 Group work areas by hanke areas in kaivuilmoitus page sidebar

---

src/domain/application/components/ApplicationContacts.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/locales/fi.json

Show kaivuilmoitus customer ("Työstä vastaava") registry key label based on whether the field can take y-tunnus, hetu or general registry key.
1. Open a kaivuilmoitus and go to contacts form page
2. Change contact type for "Työstä vastaava"
3. Label for registry key should change based on contact type selection

HAI-2626 Show customer registry key label based on contact type

---

src/common/utils/isValidPersonalId.test.ts
src/common/utils/isValidPersonalId.ts
src/common/utils/yup.ts
src/domain/application/components/ApplicationContacts.tsx
src/domain/application/yupSchemas.ts
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/validationSchema.ts
src/types/yup-extensions.d.ts

Validate kaivuilmoitus customer ("Työstä vastaava") registry keys correctly for each contact type.
1. Open kaivuilmoitus and go to contacts form page
2. Try different invalid registry keys for the customer ("Työstä vastaava")
3. Try to remove registry key
4. Validation should work for invalid or missing registry keys

HAI-2626 Validate registry keys

---

src/domain/application/components/ApplicationContacts.tsx
src/domain/application/yupSchemas.ts
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/validationSchema.ts
src/locales/fi.json

Show info text when registry key is hidden.
1. Open kaivuilmoitus and go to contacts form page
2. If the registry key is hidden there should be an info text under the text input field

HAI-2626 Show info text when the registry key is hidden

---

src/domain/application/components/ApplicationMap.tsx
src/domain/application/types/application.ts
src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/kaivuilmoitus/Areas.tsx
src/domain/map/hooks/useApplicationFeatures.ts

Kaivuilmoitus work areas are colored based on their nuisance index. This also changes a bit how the summary (maximum) of nuisance indices is calculated.
1. Create a new or open an existing kaivuilmoitus, add some work areas to it if there are not any initially
2. The color of the work areas (new or existing) on the application form should be according to its nuisance index
3. The color of the work areas in the application view should be according to its nuisance index
4. Changes to the area geometry or car traffix nuisances (kaistahaitta) should also update the area coloring

HAI-2630 Color kaivuilmoitus work areas based on their nuisance index

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/hooks/useFilterHankeAlueetByApplicationDates.ts
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/johtoselvitys/Geometries.tsx
src/domain/kaivuilmoitus/Areas.tsx
src/domain/map/HankeMap.tsx
src/domain/map/components/Layers/HankeLayer.tsx
src/domain/map/components/OwnHankeMap/OwnHankeMap.tsx
src/domain/map/types.ts
src/domain/map/utils.test.ts
src/domain/map/utils.ts

When user has entered work start and end dates in kaivuilmoitus or johtoselvitys form only show hanke areas which have duration completely within given work dates.
1. Create or edit existing kaivuilmoitus or johtoselvitys.
2. Check that when setting work dates in areas page that only hanke areas which have duration completely within given work dates are shown.

HAI-2695 Only show hanke areas in kaivuilmoitus and johtoselvitys that are fully inside work time period

---

src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx

Use the new send confirmation dialog on application forms.
1. Create a johtoselvityshakemus or kaivulupailmoitus and fill it so that it can be sent to Allu
2. Onk the last page of the  form, click the "Lähetä hakemus" button
3. A dialog should be opened where the user can choose to order a paper decision or not
4. Clicking "Vahvista" button sends the application - see that the network call contains paperDecisionReceiver data if it was selected and if it was not selected, the API call has a null body
5. If you choosed to have a paper decision, see that there is information about it on the "Yhteystiedot" tab (and if you did not choose the paper decision there should not be any information about it) …

HAI-1740 Use confirmation dialog on sending on application forms

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/components/ApplicationSendDialog.test.tsx
src/domain/application/components/ApplicationSendDialog.tsx
src/domain/application/hooks/useSendApplication.ts
src/domain/application/types/application.ts
src/domain/application/utils.ts
src/domain/application/yupSchemas.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/JohtoselvitysForm.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/locales/fi.json

On application view, "Lähetä hakemus" button opens a dialog where the user can choose to request for a paper decision.
NOTE! Implementing the same behaviour in the last page of the application form is in another PR.
1. Create a johtoselvityshakemus or kaivulupailmoitus and fill it so that it can be sent to Allu
2. In application view, click the "Lähetä hakemus" button
3. A dialog should be opened where the user can choose to order a paper decision or not
4. Clicking "Vahvista" button sends the application - see that the network call contains `paperDecisionReceiver` data if it was selected and if it was not selected, the API call has a `null` body
5. If you choosed to have a paper decision, see that there is information about it on the "Yhteystiedot" tab (and if you did not choose the …

HAI-1740 Confirmation dialog for sending application

---

src/domain/kaivuilmoitus/Areas.tsx

In kaivuilmoitus areas form page the symbol for required field was missing from work purpose selection. This adds it.
1. Open an existing or create a new kaivuilmoitus
2. Go to areas page
3. "Työn tarkoitus" selection should have the required symbol

HAI-2756 Add missing 'required' for work purpose selection

---

src/domain/application/components/ApplicationContacts.tsx
src/domain/application/utils.test.ts
src/domain/application/utils.ts
src/domain/kaivuilmoitus/Contacts.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx

Make sure that no empty string is sent in kaivuilmoitus invoicing customer: ovt, invoicingOperator, customerReference.
1. Fill kaivuilmoitus
2. In contacts page, set first the invoicing customer as a company, fills its data and then change the type to private person and fill the registry key and address to make it valid.
3. When changing the page, the API call should contain nulls instead of empty strings for the fields mentioned above

HAI-2626 Fix: Send empty strings as nulls

---

src/common/components/map/overlay/Overlay.tsx
src/common/components/map/types.ts
src/domain/application/components/ApplicationMap.tsx
src/domain/common/utils/liikennehaittaindeksi.ts
src/domain/johtoselvitys/Geometries.tsx
src/domain/kaivuilmoitus/Areas.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/components/TyoalueTable.tsx
src/domain/map/components/AreaOverlay/AreaOverlay.tsx
src/domain/map/components/Layers/HakemusLayer.tsx
src/domain/map/hooks/useApplicationFeatures.ts
src/domain/map/hooks/useHankeFeatures.ts
src/domain/map/utils/geometryStyle.test.tsx
src/domain/map/utils/geometryStyle.ts

Show areas for johtoselvitys applications that user has selected in basic information page. Johtoselvitys areas are lavender blue by color.
Also modified area overlays to match design so that hanke area overlays have background color of summer-light and application area overlays have background color of suomenlinna-light.
1. Have a johtoselvitys in hanke that has been sent to Allu
2. Create new kaivuilmoitus or edit existing one that is under same hanke than the johtoselvitys
3. In basic information page select that johtoselvitys as previously made johtoselvitys
4. Go to areas page and check that johtoselvitys areas for the selected johtoselvitys are shown in the map
other info that the …

HAI-2622 Show johtoselvitys work areas in kaivuilmoitus form areas page

---

src/domain/map/utils.ts

Rounding of hanke area coordinates was causing problems in some cases as hakemus area coordinates are not rounded, so removed rounding from hanke areas.
Also removed formatFeaturesToAlluGeoJSON function which is not used.

HAI-2829 Remove rounding of hanke area coordinates

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/components/ApplicationSendDialog.test.tsx
src/domain/application/components/ApplicationSendDialog.tsx
src/domain/application/yupSchemas.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx

Fix enabling confirm button on send dialog when trying to send after filling a new application on its last page.
Fix is implemented by removing applicationId from the dialog - it was null when a new application form was filled. ApplicationId is not needed in the dialog because the id is handled in the caller of the send confirmation.
1. Create a new johtoselvityshakemus or kaivuilmoitus, fill it until the last page
2. On the last page click "Lähetä"
3. "Vahvista" button should be enabled in the send dialog
4. Sending to Allu should work

HAI-2842 Fix enabling confirm button on send dialog

---

src/domain/application/components/ApplicationMap.tsx
src/domain/kaivuilmoitus/BasicInfo.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/map/components/AreaOverlay/AreaOverlay.test.tsx
src/domain/map/components/AreaOverlay/AreaOverlay.tsx
src/domain/map/components/JohtoselvitysSelectionMap/JohtoselvitysSelectionMap.module.scss
src/domain/map/components/JohtoselvitysSelectionMap/JohtoselvitysSelectionMap.tsx
src/domain/map/components/Layers/HakemusLayer.tsx
src/domain/map/hooks/useApplicationFeatures.ts
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

In kaivuilmoitus form basic information page, user can select which of the previously made cable report applications to use by clicking their areas on the map or pressing the button in their hover box.
1. Make sure you have some cable report applications that have been sent to Allu
2. Create or edit existing kaivuilmoitus
3. In the first page of the form try to select cable report applications by clicking their areas on the map or by clicking "Valitse johtoselvitys" button in the hover box
4. Check that they are added to the dropdown also

HAI-2818 Add map to select previous cable report applications to use in kaivuilmoitus form

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/components/summary/ContactsSummary.tsx
src/domain/application/taydennys/components/summary/JohtoselvitysAreaSummary.test.tsx
src/domain/application/taydennys/components/summary/JohtoselvitysAreaSummary.tsx
src/domain/application/taydennys/components/summary/JohtoselvitysBasicInfomationSummary.test.tsx
src/domain/application/taydennys/components/summary/JohtoselvitysBasicInformationSummary.tsx
src/domain/application/taydennys/components/summary/JohtoselvitysContactsSummary.test.tsx
src/domain/application/taydennys/components/summary/JohtoselvitysContactsSummary.tsx
src/domain/application/taydennys/types.ts
src/domain/forms/components/FormSummarySection.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennys.test.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennysContainer.tsx
src/domain/johtoselvitysTaydennys/ReviewAndSend.tsx
src/domain/johtoselvitysTaydennys/types.ts
src/domain/johtoselvitysTaydennys/validationSchema.ts
src/domain/mocks/data/hakemukset.ts
src/locales/fi.json

Show fields that have changes in summary page. There are tabs for changed fields and original data.
Check that when making changes in johtoselvitys täydennys form, they are shown in summary page in "Täydennys" tab.

HAI-2760 Show changes in johtoselvitys taydennys form summary page

---

src/common/components/HDSConfirmationDialog/ConfirmationDialog.tsx
src/domain/application/taydennys/hooks/useSendTaydennys.ts
src/domain/application/taydennys/hooks/useTaydennysSendNotification.tsx
src/domain/application/taydennys/taydennysApi.ts
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennys.test.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennysContainer.tsx
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Täydennys can be sent to Allu if it has changes and it is valid. There is a confirmation dialog before sending.
1. Make a täydennys to johtoselvitys and make some changes to some fields
2. Check that täydennys can be sent to Allu from summary page

HAI-2762 Add send button to johtoselvitys täydennys form

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/hooks/useSendTaydennys.tsx
src/domain/application/taydennys/hooks/useIsInformationRequestFeatureEnabled.ts
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennysContainer.tsx

Send täydennys button is visible if täydennys data is valid, user has EDIT_APPLICATIONS permission, hakemus Allu status is WAITING_INFORMATION and täydennys has changes.
Have a johtoselvitys täydennys with some changes and try to send it in application page.

HAI-2763 Add send täydennys button to application page

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/Sidebar.test.tsx
src/domain/application/applicationView/Sidebar.tsx
src/domain/map/components/OwnHankeMap/OwnHankeMap.tsx

If there is taydennys for application show updated and original information in tabs in side bar.
Check that johtoselvitys täydennys has "Täydennykset" and "Alkuperäiset" tabs in application page side bar displaying correct map information.

HAI-499 Show tabs for täydennykset and original information in application page side bar

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/hooks/useSendTaydennys.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennys.test.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennysContainer.tsx

If user is not added as contact person, send button is disabled and a notification is shown.
1. Have a täydennyspyyntö for johtoselvitys and start making täydennys
2. Make sure that you are not as a contact person in the form
3. Check in summary page and in application page that send täydennys button is disabled and that there is a notification "Hakemuksen voi lähettää ainoastaan hakemuksen yhteyshenkilönä oleva henkilö"

HAI-934 Make sure that user sending johtoselvitys taydennys is added as a contact person

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/taydennys/components/TaydennysCancel.tsx
src/domain/application/taydennys/taydennysApi.ts
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennys.test.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennysContainer.tsx
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Added buttons to cancel johtoselvitys täydennys to application page and johtoselvitys täydennys form.
1. Have a johtoselvitys application that has täydennyspyyntö
2. When täydennys has not been started check that "Peru täydennysluonnos" button is not visible in application page
3. Start making täydennys
4. Try cancelling täydennys either in täydennys form or in application page

HAI-779 Add buttons to cancel johtoselvitys täydennys

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/taydennys/components/summary/JohtoselvitysAreaSummary.tsx

It was decided that removed areas are not shown in johtoselvitys täydennys form summary or application view unless all areas are removed.
Check that when changing areas in johtoselvitys täydennys they are shown correctly in summary and that when removing all areas they are shown as "Poistettu".

HAI-485 Fix showing johtoselvitys täydennys areas

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/Sidebar.test.tsx
src/domain/application/applicationView/hooks/useSendTaydennys.tsx
src/domain/application/components/summary/AttachmentSummary.tsx
src/domain/application/taydennys/components/TaydennysAttachmentsList.tsx
src/domain/application/taydennys/taydennysAttachmentsApi.ts
src/domain/application/taydennys/types.ts
src/domain/forms/components/FormSummarySection.tsx
src/domain/johtoselvitysTaydennys/Attachments.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennys.test.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennysContainer.tsx
src/domain/johtoselvitysTaydennys/ReviewAndSend.tsx
src/domain/johtoselvitysTaydennys/types.ts
src/domain/johtoselvitysTaydennys/validationSchema.ts
src/domain/mocks/attachments.ts
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Make it possible to add attachments to johtoselvitys täydennys in täydennys form.
Also show original application attachments in attachments page if they exist.
1. Try to add attachments to johtoselvitys täydennys
2. Check that added attachments are shown in form attachments and summary pages and in application view
3. Check that possible original attachments are shown also

HAI-754 Johtoselvitys täydennys attachments

---

src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/ReviewAndSend.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintasuunnitelmaInfo.tsx

Show kaivuilmoitus traffic nuisance management information on summary form page.
1. Have some nuisance management plans filled in kaivuilmoitus
2. Check the summary form page and the nuisance management plan information there.

HAI-192 Show nuisance management on kaivuilmoitus summary form page

---

src/common/components/map/Map.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/__snapshots__/ApplicationView.test.tsx.snap
src/domain/common/haittojenhallinta/utils.test.ts
src/domain/common/haittojenhallinta/utils.ts
src/domain/kaivuilmoitus/Areas.tsx
src/domain/kaivuilmoitus/HaittojenHallinta.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintaMap.module.scss
src/domain/kaivuilmoitus/components/HaittojenhallintaMap.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintaSuunnitelma.tsx

Maps show hanke and work areas coloured by corresponding liikennemuoto haittaindex.
Check that haittojenhallinta maps show areas coloured correctly.

HAI-678 Add maps for each liikennemuoto to kaivuilmoitus haittojenhallinta

---

src/common/components/customAccordion/CustomAccordion.tsx
src/domain/common/haittojenhallinta/useIsHaittojenhallintaSectionVisible.ts
src/domain/hanke/edit/components/Haittojenhallintasuunnitelma.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintaSuunnitelma.tsx

If Haitaton has not detected nuisances for some liikennemuoto text that nuisance is not detected and a button to add haittojenhallintatoimet is shown. If user presses the button field to add haittojenhallintatoimet is shown instead.
1. Add work areas to kaivuilmoitus in such way that some liikennemuoto has a haittaindex 0, for example pyöräliikenne
2. Check in the haittojenhallinta page that for that liikennemuoto there is a text "Haitaton ei löytänyt tätä kohderyhmää alueelta. Voit tarvittaessa lisätä toimet haittojen hallintaan." and a button "Lisää toimet haittojen hallintaan"
3. Click the button
4. The text and the button should be replaced with text area
other info that the tester/user needs …

HAI-131 Kaivuilmoitus haittojenhallintatoimet for non-detected liikennemuodot

---

src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennys.test.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennysContainer.tsx

Add Cancel button on kaivuilmoitus täydennys form
1. Create a täydennyspyyntö for kaivuilmoitus
2. Open täydennys form
3. There should be cancel button which should bring the user back to application view and remove the täydennys

HAI-3296 Add Cancel button on kaivuilmoitus täydennys form

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennys.test.tsx
src/domain/kaivuilmoitusTaydennys/Attachments.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennys.test.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennysContainer.tsx
src/domain/kaivuilmoitusTaydennys/types.ts
src/domain/kaivuilmoitusTaydennys/validationSchema.ts
src/domain/mocks/attachments.ts
src/locales/fi.json

Attachments page shows original attachments added to kaivuilmoitus. It's also possible to add new attachments and remove those.
1. Try to add attachments to kaivuilmoitus täydennys
2. Check that possible original attachments are shown also

HAI-3295 Add attachments page to kaivuilmoitus taydennys form

---

src/domain/application/taydennys/components/TaydennysAttachmentsList.tsx
src/domain/application/taydennys/components/summary/ContactsSummary.test.tsx
src/domain/application/taydennys/components/summary/ContactsSummary.tsx
src/domain/application/taydennys/components/summary/KaivuilmoitusAreaSummary.test.tsx
src/domain/application/taydennys/components/summary/KaivuilmoitusAreaSummary.tsx
src/domain/application/taydennys/components/summary/KaivuilmoitusBasicInformationSummary.test.tsx
src/domain/application/taydennys/components/summary/KaivuilmoitusBasicInformationSummary.tsx
src/domain/application/taydennys/components/summary/KaivuilmoitusHaittojenhallintaSummary.test.tsx
src/domain/application/taydennys/components/summary/KaivuilmoitusHaittojenhallintaSummary.tsx
src/domain/johtoselvitysTaydennys/ReviewAndSend.tsx
src/domain/kaivuilmoitus/ReviewAndSend.tsx
src/domain/kaivuilmoitus/components/AreaSummary.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintaSummary.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintasuunnitelmaInfo.module.scss
src/domain/kaivuilmoitus/components/HaittojenhallintasuunnitelmaInfo.tsx
src/domain/kaivuilmoitus/components/TyoalueTable.tsx
src/domain/kaivuilmoitus/hooks/useFormErrorsByPage.ts
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennysContainer.tsx
src/domain/kaivuilmoitusTaydennys/ReviewAndSend.tsx
src/locales/fi.json

There are täydennykset and alkuperäiset tabs in summary page. Alkuperäiset tab displays the original data of the application. Täydennykset tab displays only information that has changed.
Check that when making changes in kaivuilmoitus täydennys form, they are shown in summary page in "Täydennykset" tab.

HAI-3322 Add summary page to kaivuilmoitus taydennys form

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/hooks/useSendTaydennys.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennys.test.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennysContainer.tsx

Show "Lähetä täydennys" button in kaivuilmoitus form summary page and in application view.
Also, added tests for sending + copied other täydennys tests from johtoselvitys täydennys.
1. Create a täydennys for kaivuilmoitus
2. Make some changes in täydennys
3. Check that "Lähetä täydennys" button is shown in summary page and in application view

HAI-3325 Add send button for kaivuilmoitus taydennys

---

src/common/components/map/utils.test.ts
src/common/components/map/utils.ts
src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/Sidebar.test.tsx
src/domain/application/applicationView/__snapshots__/ApplicationView.test.tsx.snap
src/domain/application/taydennys/components/summary/JohtoselvitysAreaSummary.test.tsx
src/domain/application/taydennys/components/summary/KaivuilmoitusAreaSummary.test.tsx
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/mocks/data/hakemukset-data.ts

The area was calculated on a spherical surface, but the projection we use is projected on a flat plane, so the area calculations were wrong.
Use `Polygon.getArea()` to properly calculate the area to use the flat projection.

Fix area calculation

---

src/domain/application/yupSchemas.ts
src/domain/forms/components/FormFieldsErrorSummary.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/components/FormErrorsNotification.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintaSuunnitelma.tsx
src/domain/kaivuilmoitus/mapValidationErrorToErrorListItem.test.ts
src/domain/kaivuilmoitus/mapValidationErrorToErrorListItem.tsx
src/domain/kaivuilmoitus/validationSchema.ts
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennysContainer.tsx

Notification shows validation errors in each page and list of pages with errors in the summary page.
Also added the list of pages with errors to kaivuilmoitus taydennys summary page.
Check that when editing kaivuilmoitus form validation errors for current page are shown in notification in top of the form and a list of pages with errors in summary page.

HAI-769 Add notification to kaivuilmoitus form to show summary of validation errors

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/hooks/useSaveApplication.ts
src/domain/forms/MultipageForm.tsx
src/domain/forms/components/FormPagesErrorSummary.tsx
src/domain/forms/formStepReducer.ts
src/domain/forms/types.ts
src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/hankeView/HankeView.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/components/FormErrorsNotification.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennysContainer.tsx

There was a problem with validation context object not updating when making changes to hanke or work areas. This caused problems for haittojenhallinta liikennemuoto fields validation which depend on context given to validation.
Fixed this by making sure context object is always updated when saving in hanke, kaivuilmoitus and kaivuilmoitus taydennys forms.
1. Create new kaivuilmoitus
2. Create work area(s) so that for example "Raitioliikenne" and "Linja-autojen paikallisliikenne" have haittaindeksi above 0
3. Go to haittojenhallinta page and check that those liikennemuodot haittojenhallinta fields are required and that those errors are shown in notification on top of the form
4. Go back to alueet page and change area(s) so that at least one of those previously required fields become …

HAI-131 Fix validation context for haittojenhallinta in hanke and kaivuilmoitus

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/Sidebar.test.tsx
src/domain/application/applicationView/Sidebar.tsx
src/domain/application/components/summary/InvoicingCustomerSummary.tsx
src/domain/application/components/summary/KaivuilmoitusAttachmentSummary.tsx
src/domain/application/components/summary/KaivuilmoitusBasicInformationSummary.tsx
src/domain/application/taydennys/components/summary/ContactsSummary.tsx
src/domain/application/taydennys/components/summary/KaivuilmoitusHaittojenhallintaSummary.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintaSummary.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintasuunnitelmaInfo.tsx
src/domain/mocks/data/hakemukset-data.ts
src/locales/fi.json

Show kaivuilmoitus täydennys information in application view.
Also, this implements issue https://helsinkisolutionoffice.atlassian.net/browse/HAI-3297
1. Create a täydennys for kaivuilmoitus
2. Do changes in täydennys
3. Check the application view for täydennys changes (check also the map in sidebar (HAI-3297))
4. Check also that regular kaivuilmoitus does not have any täydennys sections in application view

HAI-3293 Kaivuilmoitus täydennys data in application view

---

src/domain/common/haittaIndexes/utils.test.ts
src/domain/common/haittaIndexes/utils.tsx
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormAlueet.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/types.ts
src/locales/fi.json

In hanke form areas page for public hanke when changing hanke areas and haitta indexes are recalculated, if index for any liikennemuoto is increased, alert notification is displayed for user that haitta indexes have changed.
1. Edit hanke that is public
2. Edit hanke area geometry or nuisance estimates (for example nuisance start date or dust nuisance) so that nuisance index of any liikennemuoto is increased)
3. There should appear a notification "Hankealueille lasketut liikennehaittaindeksit ovat muuttuneet. Tarkista haittojenhallintasuunnitelma." under the map

HAI-628 Show notification if haitta indexes increase when changing hanke areas

---

src/domain/common/haittaIndexes/ProcedureTips.tsx
src/domain/common/haittaIndexes/__snapshots__/ProcedureTips.test.tsx.snap
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintaSuunnitelma.tsx

Adds nuisance control tip accordions to kaivuilmoitus
Nuisance control tips are shown in kaivuilmoitus. They are hidden by default if the index is zero for the area.

HAI-681: Add nuisance control tips to kaivuilmoitus

---

src/domain/map/components/FeatureInfoOverlay/FeatureInfoOverlay.tsx
src/domain/map/components/Layers/HakemusLayer.tsx
src/domain/map/components/OwnHankeMap/OwnHankeMap.tsx
src/domain/map/hooks/useApplicationFeatures.ts
src/domain/map/hooks/useHankeFeatures.ts

Show info hover overlay in hanke and application view maps.
1. Have some applications and work areas in them
2. Check application view map - the name of hanke area with the name of the work area should be shown in hover overlay
3. Check hanke view map - the name of hanke area should be shown in hover overlay

HAI-133 Show info hover on hanke and hakemus areas

---

src/domain/map/components/Layers/Kantakartta.tsx

For easier navigation and better experience for user when drawing hanke and work areas added 'Kiinteistokartan_maastotiedot' layer between 'Kantakartta' and 'Opaskartta_Helsinki' layers, which has maxZoom 10 and minZoom 8 and changed 'Kantakartta' minZoom from 9 to 10.
Also added 'Opaskartta_Helsinki_harvanimi' after 'Opaskartta_Helsinki' with maxZoom 7 and set 'Opaskartta_Helsinki' maxZoom to 8 and minZoom to 7.
Check that layers in maps match https://kartta.hel.fi except that there are no "Yleiskartta" layers on outer zoom levels.

HAI-682 Add two WMS layers for different zoom levels to maps

---

src/domain/application/components/ApplicationListItem.tsx
src/domain/hanke/hankeView/HankeView.test.tsx

Changed testid to use application identifier if available or application id otherwise as was before.

Change testid in application list item link to application view

---

src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/components/Haitat.tsx
src/domain/hanke/edit/utils.tsx
src/locales/fi.json

In Hanke form Alueet page when user tries to delete an area, check whether there are any application areas inside the hanke area and if so, show a dialog and prevent the user from deleting the area.
Implemented for both johtoselvityshakemus and kaivuilmoitus at the same time.
1. Create a hanke or use an existing one
2. Create some applications for the hanke or use existing ones
3. Try to delete hanke areas that contain application areas - do the same for hanke areas that do not include any application areas
4. Check also that if application does not yet have any areas (only the first page has been filled) the system works okay

HAI-2088 Show dialog and prevent deletion of hanke area if there are application areas inside it

---

src/domain/common/haittojenhallinta/CommonProcedureTips.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintaSuunnitelma.tsx
src/domain/kaivuilmoitus/components/HaittojenhallintasuunnitelmaInfo.tsx
src/locales/fi.json

Adds showing hanke nuisance control index and procedures within kaivuilmoitus form.
Open Kaivuilmoitus form. Hanke nuisance control procedures are indexes should be visible.

HAI-551: Add hanke nuisance control info to kaivuilmoitus

---

src/domain/kaivuilmoitus/validationSchema.ts

Fix issue in kaivuilmoitus and kaivuilmoitus täydennys forms summary page where list of pages with validation errors would not show areas page if work areas were missing entirely.
Remove all work areas in kaivuilmoitus or kaivuilmoitus täydennys form and check that areas page is listed in summary page in error notification.

HAI-3298 Fix areas page name not showing in pages with errors list in form summary page

---

src/common/utils/yup.ts
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/edit/components/Haitat.tsx
src/domain/hanke/edit/hankeSchema.ts
src/domain/hanke/edit/utils.tsx
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/map/HankeMap.test.tsx
src/domain/mocks/data/hakemukset-data.ts
src/domain/mocks/data/hankkeet-data.ts
src/locales/fi.json
src/types/yup-extensions.d.ts

Prevent changing hanke area dates to be outside of the dates of the applications that have work areas in that hanke area.
This implementation also changes the implementation of https://github.com/City-of-Helsinki/haitaton-ui/pull/1064.
1. Have a hanke with applications (of both types) with areas inside different hanke areas and with variable dates
2. Try to change hanke area dates to be outside of the date limits of the applications that have work areas in that hanke area
3. Check that the date picker does not allow to choose invalid dates
4. Check that when typing an invalid date by hand there is a validation error message shown
5. With invalid date user cannot change form page
6. (Saving the form is still possible with invalid dates but that will be fixed when the backend prevents …

HAI-1242 Validate hanke area dates against application work areas

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/ApplicationViewContainer.tsx
src/domain/application/muutosilmoitus/hooks/useCreateMuutosilmoitus.ts
src/domain/application/muutosilmoitus/muutosilmoitusApi.ts
src/domain/application/muutosilmoitus/types.ts
src/domain/application/taydennys/taydennysApi.ts
src/domain/application/types/application.ts
src/domain/johtoselvitys/types.ts
src/domain/kaivuilmoitus/types.ts
src/domain/kaivuilmoitusTaydennys/types.ts
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Button is shown if kaivuilmoitus has Allu status DECISION or OPERATIONAL_CONDITION and user has EDIT_APPLICATIONS permission.
Clicking the button calls POST /hakemukset/:id/muutosilmoitus, but nothing else happens at this point. The actual muutosilmoitus form and navigating to it will be implemented later.
1. Check that create muutosilmoitus button is shown for kaivuilmoitus when Allu status is DECISION or OPERATIONAL_CONDITION (and that it is not shown for johtoselvitys even in DECISION status)
2. Click the button and check in browser dev tools network tab that POST /hakemukset/:id/muutosilmoitus is called

HAI-3396 Add create muutosilmoitus button to kaivuilmoitus application view

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/hanke/hooks/useHaittaIndexes.ts
src/domain/kaivuilmoitus/Areas.tsx
src/domain/kaivuilmoitus/utils.test.ts
src/domain/kaivuilmoitus/utils.ts
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennysContainer.tsx

Notification in kaivuilmoitus täydennys form areas page when nuisance indexes change. Also, fixed equality check of index changes in täydennys application view.
1. Create a kaivuilmoitus and täydennys for it
2. Change areas in kaivuilmoitus täydennys
3. If the changes also change the nuisance indexes, a notification is shown
4. Also, a notification is shown in täydennys application view areas tab (was already before but the equality check was incorrect)

HAI-3341 Notify if kaivuilmoitus täydennys changes nuisance indexes

---

src/domain/kaivuilmoitus/HaittojenHallinta.tsx
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/mapValidationErrorToErrorListItem.test.ts
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennys.test.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Also changed Toimet työalueiden haittojen hallintaan label to Yleiset toimet työalueiden haittojen hallintaan for yleiset toimet text area.

HAI-424 Fix tab names in kaivuilmoitus form haittojenhallinta page

---

src/domain/application/applicationView/Sidebar.test.tsx
src/domain/application/applicationView/Sidebar.tsx
src/locales/fi.json

In similar way to täydennys, muutosilmoitus area information is displayed in tabs along with original application area information in application view sidebar.
1. Have a kaivuilmoitus for which muutosilmoitus can be made (in decision or operational condition state)
2. Start making muutosilmoitus and make changes to work areas
3. Save and quit the form and check in application view that there are "Muutokset" and "Alkuperäiset" tabs in sidebar that show the correct information

HAI-430 Show muutosilmoitus work areas in application view sidebar

---

src/common/utils/yup.ts
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx

There was a problem in kaivuilmoitus form haittojenhallinta page that validation errors might be shown for liikennemuodot that have nuisance index 0 (which are optional and no error should be shown). This was happening if there were work areas in multiple hanke areas as nuisance indexes were checked always only on the first area. Fixed this by finding the area path segment based on if it includes 'alueet' or 'areas' instead of taking the first path segment as the first segment for hakemus is 'applicationData'.
Have a kaivuilmoitus that have work areas in multiple hanke areas so that the first area has for example raitioliikenne or linja-autoliikenne nuisance index above 0 but for other area(s) that same index is 0 and check that unnecessary validation errors are not shown.
or other …

HAI-221 Don't show validation errors for undetected liikennemuodot

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/kaivuilmoitus/utils.ts

Handle adding work areas to new hanke areas correctly. Do the same with hanke areas that no longer have work areas.
1. Have a hanke that has at least 3 areas
2. Have a kaivuilmoitus with a work areas in 2 hanke areas
3. Have a täydennyspyyntö and täydennys for kaivuilmoitus
4. In täydennys, remove a work area in one hanke area and add a new work area in new hanke area
5. Check that application view shows areas and haittojen hallinta correctly

HAI-3293 Fix not showing work areas in new hanke areas

---

Dockerfile
Dockerfile-local
nginx/nginx.conf

Use the Red Hat Universal Base Image 9 based images for building the
image for haitaton-ui.
NOTE: The headers more module can not be installed on RHEL without a
commercial nginx subscription, so we can't remove the server header from
responses. The version of the nginx will still be hidden.

HAI-3369 Use UBI9 base images

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/ApplicationViewContainer.tsx
src/domain/application/applicationView/Sidebar.test.tsx
src/domain/application/muutosilmoitus/types.ts
src/domain/application/taydennysAndMuutosilmoitusCommon/MuutosLabelContext.tsx
src/domain/forms/components/FormSummarySection.tsx
src/domain/kaivuilmoitusMuutosilmoitus/KaivuilmoitusMuutosilmoitus.test.tsx
src/domain/mocks/data/hakemukset-data.ts
src/domain/mocks/data/hakemukset.ts
src/locales/fi.json

Changes made in kaivuilmoitus muutosilmoitus form are shown in application view in the same way as täydennys changes.
Make changes in kaivuilmoitus muutosilmoitus form and check that changes are shown correctly in application view.

HAI-3405 Show muutosilmoitus changes in application view

---

src/common/components/fileUpload/FileUpload.module.scss
src/common/components/fileUpload/FileUpload.tsx
src/common/components/inlineModal/InlineModal.scss
src/common/components/inlineModal/InlineModal.tsx
src/domain/hanke/edit/HankeForm.tsx
src/domain/hanke/edit/HankeFormLiitteet.tsx
src/domain/johtoselvitys/Attachments.tsx
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitysTaydennys/Attachments.tsx
src/domain/johtoselvitysTaydennys/JohtoselvitysTaydennysContainer.tsx
src/domain/kaivuilmoitus/Attachments.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitusTaydennys/Attachments.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennysContainer.tsx

Moved file upload loading element inside modal to block other interactions in the site while files are being uploaded. Only upload cancel button is usable.
Removed file upload loading states from buttons in hanke, johtoselvitys, johtoselvitys täydennys, kaivuilmoitus and kaivuilmoitus täydennys forms.
1. Try to upload attachments in hanke, johtoselvitys and kaivuilmoitus forms
2. When uploading is ongoing check that only cancel button is usable in the whole page

HAI-3452 Add loading overlay for file upload loading state

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/kaivuilmoitusMuutosilmoitus/KaivuilmoitusMuutosilmoitusContainer.tsx

Display form validation errors in kaivuilmoitus muutosilmoitus form in similar way as in other forms. Also add muutosilmoitus data to FormPagesErrorSummary in application view to show pages with errors there as well.
Check that validation errors are shown in kaivuilmoitus muutosilmoitus form in similar way than in other kaivuilmoitus forms.

HAI-367 Add validation error notification to kaivuilmoitus muutosilmoitus form

---

src/common/components/HDSConfirmationDialog/ConfirmDialog.test.tsx
src/common/components/HDSConfirmationDialog/ConfirmationDialog.module.scss
src/common/components/HDSConfirmationDialog/ConfirmationDialog.tsx
src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/Sidebar.tsx
src/domain/application/muutosilmoitus/components/MuutosilmoitusCancel.tsx
src/domain/application/muutosilmoitus/muutosilmoitusApi.ts
src/domain/application/types/application.ts
src/domain/kaivuilmoitusMuutosilmoitus/KaivuilmoitusMuutosilmoitus.test.tsx
src/domain/kaivuilmoitusMuutosilmoitus/KaivuilmoitusMuutosilmoitusContainer.tsx
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Add cancel functionality for muutosilmoitus.
Also, change some (just a few) Button components to not use deprecated parameters `isLoading` and `loadingText` in order to make it a bit easier to move into newer HDS version.
1. Have a kaivuilmoitus with decision
2. Create a muutosilmoitus for it
3. Cancel the muutosilmoitus from application view or the form
4. Muutosilmoitus should be cancelled

HAI-3407 Add cancel functionality for muutosilmoitus

---

src/domain/application/applicationView/ApplicationView.test.tsx
src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/hooks/useSendMuutosilmoitus.tsx
src/domain/application/components/ApplicationSendDialog.test.tsx
src/domain/application/components/ApplicationSendDialog.tsx
src/domain/application/hooks/useApplicationSendNotification.tsx
src/domain/application/hooks/useSendApplication.ts
src/domain/application/muutosilmoitus/muutosilmoitusApi.ts
src/domain/johtoselvitys/JohtoselvitysContainer.tsx
src/domain/johtoselvitys/types.ts
src/domain/johtoselvitys/validationSchema.ts
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/domain/kaivuilmoitus/types.ts
src/domain/kaivuilmoitus/validationSchema.ts
src/domain/kaivuilmoitusMuutosilmoitus/KaivuilmoitusMuutosilmoitus.test.tsx
src/domain/kaivuilmoitusMuutosilmoitus/KaivuilmoitusMuutosilmoitusContainer.tsx
src/domain/mocks/data/hakemukset.ts
src/domain/mocks/handlers.ts
src/locales/fi.json

Sending muutosilmoitus for both muutosilmoitus form and application view.
1. Create a muutosilmoitus for a kaivuilmoitus
2. Make a change
3. Send button should be availabe when there are changes (and the user has correct rights)
4. Send dialog should work without paper decision and with it
5. The same send dialog is used for sending applications, so that should also be tested that it still works as before

HAI-3409 Implementation for sending muutosilmoitus

---

.env.e2e.example
e2e/_setup.ts
e2e/johtoselvitys_ja_liite_hankkeelle.spec.ts
e2e/johtoselvitys_tilaus_taydennyspyynto.spec.ts
e2e/kaivuilmoitus_taydennyspyynto.spec.ts
e2e/kaivuilmoitus_toiminnallinen_kunto.spec.ts

Add calls to manually trigger Allu updates to E2E tests. The call will trigger Allu status updates instantly in the backend, so there's no need to wait up to 60 seconds for the next update. The trigger is available only in test environments, but we can't and don't want to run the e2e test against production.
I left the wait loops untouched, in case there's a delay in Allu having the status update in the status history.
Run the tests. One test was already failing for me, I didn't attempt to fix it.

HAI Add Allu trigger calls to E2E tests

---

src/domain/application/components/ApplicationSendDialog.tsx
src/domain/application/yupSchemas.ts

Fix bug with send dialog when the confirm button was disabled even when it should have been enabled.
1. Try sending with a kaivuilmoitus and set paper decision to true and fill the details and send it (test toggling too)
2. Create päätös for it in Allu
3. Create a muutosilmoitus for it and change some data so that it can be sent
4. Send dialog should now have the paper decision data filled as default
5. Toggling the button should work and confirmation button be enabled or disabled correctly even with cancelling and sending again

HAI-3409 Enable and disable the confirm send button correctly

---

src/domain/kaivuilmoitus/components/TyoalueTable.tsx
src/domain/map/utils.ts

When drawing kaivuilmoitus work areas a notification is shown if the work area is not fully contained inside a johtoselvitys area. This had a bug that checked only the work area geometry points and not the whole geometry including its sides. This PR fixes this bug using the same functionality as a previous fix where hanke area could not have been changed to be smaller than work areas inside it.
This is how I tested this:
1. Create a hanke with similar geometry as in Jira ticket
2. Create a johtoselvitys for the hanke with similar area as in Jira ticket
3. Send johtoselvitys and create a päätös for it in Allu
4. Create a kaivuilmoitus for the hanke using the johtoselvitys
5. Try to draw a similar work area as in Jira ticket - now it should show notification where previously it did not
or …

HAI-2421 Fix checking whether johtoselvitys area contains work area

---

src/domain/hanke/components/HankeStatusTag.module.scss
src/domain/hanke/components/HankeStatusTag.test.tsx
src/domain/hanke/components/HankeStatusTag.tsx
src/domain/hanke/hankeView/HankeView.test.tsx
src/domain/hanke/hankeView/HankeView.tsx
src/locales/fi.json

Show completed status tag in hanke view.
Also, show draft status tag and hanke duration (as in Figma).
Also, do not show draft status notification (with missing data) if hanke is completed.
1. Have a hanke that is completed
2. Check hanke view for status tag
3. Check status tag for a draft hanke as well
4. Check that duration is shown in hanke view (if hanke is draft and has no start and end dates, there is just a dash (-))

HAI-137 Show completed status in hanke view

---

src/domain/hanke/accessRights/AccessRightsView.test.tsx
src/domain/hanke/accessRights/AccessRightsView.tsx
src/domain/mocks/data/users-data.json

Allow resending invitation for completed hanke.
1. Have a completed hanke with some new contact persons (a completed hanke can be created by creating a hanke with dates in the past and setting in the backend `HankeCompletionScheduler.completeHankkeet()` to have annotation `@EventListener(ApplicationReadyEvent::class)` or by setting `haitaton.hanke.completions.cron = 0 * * * * *` in `application yml` or running the backend with `HAITATON_COMPLETIONS_CRON="0 * * * * *"`.
2. Check that you can resend the invitation to contact persons in user management of the hanke

HAI-1149 Allow resending invitation for completed hanke

---

package.json
src/domain/kaivuilmoitus/KaivuilmoitusForm.test.tsx
src/domain/kaivuilmoitus/components/TyoalueTable.tsx
src/domain/map/utils.ts
yarn.lock

There was a problem that notification for kaivuilmoitus work area exceeding johtoselvitys area(s) was shown even if multiple johtoselvitys areas would cover the work area. Fixed that by checking if the work area is also within union of intersecting johtoselvitys areas.
Try steps described in https://helsinkisolutionoffice.atlassian.net/browse/HAI-2493.

HAI-2493 Fix notification shown when kaivuilmoitus work area within johtoselvitys areas union

---

src/domain/hanke/edit/utils.tsx
src/domain/kaivuilmoitus/Areas.tsx
src/domain/map/utils.ts
src/domain/map/utils/isFeatureWithinFeatures.ts

Work area is possible to draw so that the corner points are inside the hanke area but the boundary is outside of area. 
This change will check that the entire work area is inside the hanke area.
https://helsinkisolutionoffice.atlassian.net/browse/HAI-2476
- [x ] Other

Hai 2476 kaivuilmoitus geometria ylitys

---

src/domain/application/components/ApplicationMap.tsx
src/domain/kaivuilmoitus/Areas.tsx
src/domain/map/components/HankeDrawer/HankeDrawer.tsx

After area is selected or modified, area is selected and correct tab is activated. This adds calls to selecting the feature into modifyEnd handlers in both hanke and kaivuilmoitus form area pages.
* In Hanke form: Have multiple areas. Click an area or change its geometry. Correct area tab is activated.
* In Kaivuilmoitus form. Place work area inside different hanke areas. Click a work area or change its geometry. Correct hanke area tab is activated and correct work area is selected in the list.

HAI-1416: Modifying area selects the area and changes tab

---

nginx/nginx.conf
public/scripts/init-matomo.js
src/globals.d.ts
src/index.tsx

Add into nginx Content-Security-Policy header hel.fi Matomo access.
1. Run both the backend and the frontend with Docker Compose
2. Check that Cookie Consent banner works okay and there are no Content-Security-Policy errors in console.

HAI-1688 Fix matomo script loading and cookie consent banner

---

src/domain/application/applicationView/ApplicationView.tsx
src/domain/application/applicationView/Sidebar.test.tsx
src/domain/application/taydennys/components/summary/JohtoselvitysAreaSummary.tsx
src/domain/application/taydennysAndMuutosilmoitusCommon/components/summary/KaivuilmoitusAreaSummary.test.tsx
src/domain/application/taydennysAndMuutosilmoitusCommon/components/summary/KaivuilmoitusAreaSummary.tsx
src/domain/application/taydennysAndMuutosilmoitusCommon/components/summary/KaivuilmoitusHaittojenhallintaSummary.test.tsx
src/domain/application/taydennysAndMuutosilmoitusCommon/components/summary/KaivuilmoitusHaittojenhallintaSummary.tsx
src/domain/application/taydennysAndMuutosilmoitusCommon/utils.ts
src/domain/johtoselvitys/components/AreaSummary.tsx
src/domain/johtoselvitys/utils.ts
src/domain/kaivuilmoitusMuutosilmoitus/ReviewAndSend.tsx
src/domain/kaivuilmoitusTaydennys/KaivuilmoitusTaydennys.test.tsx
src/domain/kaivuilmoitusTaydennys/ReviewAndSend.tsx
src/domain/map/utils.ts
src/domain/mocks/data/hakemukset-data.ts

Show changes in kaivuilmoitus areas and haittojenhallintasuunnitelma in summary form page for täydennys and muutosilmoitus. Show changes in areas also in johtoselvitys täydennys.
1. Create first a täydennys for kaivuilmoitus and johtoselvityshakemus
2. Change areas (remove all from some hanke area and add new ones in hanke areas that didn't have any application areas) (and haittojenhallintasuunnitelma for kaivuilmoitus)
3. Check summary page
4. Create päätös and then muutosilmoitus for kaivuilmoitus
5. Again, make some changes in areas and haittojenhallintasuunnitelma
6. Check summary page

HAI-3470 Fixes in areas in kaivuilmoitus and johtoselvitys form summary pages

---

src/domain/application/applicationView/Sidebar.tsx
src/domain/hanke/hankeView/HankeView.tsx
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/domain/map/components/OwnHankeMap/OwnHankeMapHeader.tsx

Do not show link to full page map in hanke view and list. The functionality still is in place but everywhere its use is set to `false`.
Other thing in Jira issue was to remove "Päätä hanke" button from hanke view. That is already implemented in https://github.com/City-of-Helsinki/haitaton-ui/pull/1149
1. Check that there is no "Avaa kartta uuteen ikkunaan" links in hanke list or hanke view.

HAI-3472 Do not show link to full page map in hanke view and list

---

src/domain/hanke/portfolio/HankePortfolio.test.tsx
src/domain/hanke/portfolio/HankePortfolioComponent.tsx
src/pages/EditJohtoselvitysPage.test.tsx

Do not show hanke edit link in hanke list if hanke is completed.
1. Have some completed hanke
2. Check that there is no edit link (pen) in hanke list for that hanke

HAI-3557 Prevent editing hanke from list

---

src/domain/common/haittojenhallinta/utils.ts
src/domain/hanke/edit/HankeForm.test.tsx
src/domain/hanke/edit/HankeFormSummary.tsx
src/domain/hanke/edit/components/HaittojenhallintaSummary.tsx
src/domain/hanke/edit/components/HaittojenhallintasuunnitelmaInfo.module.scss
src/domain/hanke/edit/components/HaittojenhallintasuunnitelmaInfo.tsx

Add haittojenhallintasuunnitelma on hanke form summary page
1. Create hanke, add some areas and fill haittojenhallintasuunnitelma for them
2. Check the summary form page that it is according to specs

HAI-3530 Add haittojenhallintasuunnitelma on hanke form summary page

---

src/pages/staticPages/workInstructions/cards/Cards.tsx

Add missing breadcrumb from work instruction sub pages.
Work instructions breadcrumb visible in card pages.

HAI-3504: Add missing breadcrumb

---

src/domain/kaivuilmoitus/Areas.tsx

If end date of the nuisance is removed do not call calculateHaittaIndexesForTyoalue
calculateHaittaIndexesForTyoalue added prevent calculation if dates are empty
https://helsinkisolutionoffice.atlassian.net/browse/HAI-3578

nuisance end date removed

---

src/common/components/datePicker/DatePicker.tsx
src/domain/kaivuilmoitus/Areas.tsx
src/domain/kaivuilmoitus/KaivuilmoitusContainer.tsx
src/locales/fi.json

If you enter a date that is too early in the start date field, the field will be cleared and an error message will tell what the earliest possible date is.
The same function is used for the end date.
When the date field is cleared, you will not be able to proceed on the page, meaning the excavation report will not be saved.
- [X ] Bug fix

Preventing false dates on workarea

---

TESTING_SESSION_TERMINATION.md
src/common/components/app/App.tsx
src/common/components/datePicker/DatePicker.tsx
src/domain/api/api.test.ts
src/domain/api/api.ts
src/domain/auth/components/SessionTerminationHandler.test.tsx
src/domain/auth/components/SessionTerminationHandler.tsx
src/locales/en.json
src/locales/fi.json
src/locales/sv.json

Log out when the backend has logged out (via backchannel-logout call from Helsinki Profiili).
The logic of logging out this way is explained in TESTING_SESSION_TERMINATION.md
See the backend PR: https://github.com/City-of-Helsinki/haitaton-backend/pull/1128

HAI-3541 Log out when the backend has logged out
